[workspace]
members = [
    "bins/emmbedig-calculator",
    "bins/emmbeding-clustering",
    "bins/questions-extractor",
    "bins/sureall-db-rig",
    "bins/tg-messages-colector",
    "libs/chat-types",
    "bins/crm-chat-app/src-tauri",
    "bins/sdb_server",
    "libs/sdb_api",
    "libs/messanger-inteface",
    "libs/messanger-telegram", "bins/telegram-subscriber",
]
resolver = "3"
