// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import ChatType from "./chat_type_type";


export default __t.object("Chat", {
  id: __t.string(),
  ownerUserId: __t.identity(),
  clientId: __t.u64(),
  get chatType() {
    return ChatType;
  },
  isPinned: __t.bool(),
  pinnedName: __t.option(__t.string()),
  lastMessageTs: __t.u64(),
});


