// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

// The tagged union or sum type for the algebraic type `ClientStatus`.
const ClientStatus = __t.enum("ClientStatus", {SendingLoginCode: __t.string(),
  ReceivingLoginCode: __t.string(),
  VerifyingLoginCode: __t.string(),
  ReceivingPassword: __t.string(),
  VerifyingPassword: __t.string(),
  GeneratingQrCode: __t.string(),
  Connected: __t.unit(),
  Error: __t.string(),
});

export default ClientStatus;


