// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import ClientKind from "./client_kind_type";
import ClientStatus from "./client_status_type";


export default __t.row({
  id: __t.u64().primaryKey(),
  ownerUserId: __t.identity(),
  get kind() {
    return ClientKind;
  },
  externalId: __t.string(),
  activeChats: __t.array(__t.u64()),
  get status() {
    return ClientStatus;
  },
});
