// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import SignInSuccess from "./sign_in_success_type";
import QrToken from "./qr_token_type";


// The tagged union or sum type for the algebraic type `GenerateQrCodeOutput`.
const GenerateQrCodeOutput = __t.enum("GenerateQrCodeOutput", {Pending: __t.unit(),
  get Token() {
    return QrToken;
  },
  get Authorized() {
    return SignInSuccess;
  },
  get AlreadyAuthorized() {
    return SignInSuccess;
  },
  Cancelled: __t.unit(),
  Failed: __t.string(),
});

export default GenerateQrCodeOutput;


