// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  externalId: __t.string(),
  ownerUserId: __t.identity(),
  clientId: __t.u64(),
  chatId: __t.string(),
  senderId: __t.string(),
  text: __t.option(__t.string()),
  out: __t.bool(),
  deleted: __t.bool(),
  ts: __t.u64(),
  mediaId: __t.option(__t.u64()),
});
