// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import PhoneAuthStep from "./phone_auth_step_type";


export default __t.row({
  id: __t.u64().primaryKey(),
  ownerUserId: __t.identity(),
  clientId: __t.u64(),
  phone: __t.string(),
  get step() {
    return PhoneAuthStep;
  },
  phoneCodeHash: __t.option(__t.string()),
  loginCode: __t.option(__t.string()),
  passwordToken: __t.option(__t.string()),
  password: __t.option(__t.string()),
  passwordHint: __t.option(__t.string()),
  error: __t.option(__t.string()),
  assignedRobot: __t.option(__t.identity()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
