// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import QrAuthStep from "./qr_auth_step_type";


export default __t.row({
  id: __t.u64().primaryKey(),
  ownerUserId: __t.identity(),
  get step() {
    return QrAuthStep;
  },
  qrUrl: __t.option(__t.string()),
  qrExpires: __t.option(__t.i32()),
  telegramUserId: __t.option(__t.i64()),
  error: __t.option(__t.string()),
  assignedRobot: __t.option(__t.identity()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
