// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import ReceivePasswordOutput from "./receive_password_output_type";


export default __t.object("ReceivePassword", {
  clientPhone: __t.string(),
  hint: __t.option(__t.string()),
  token: __t.string(),
  get output() {
    return ReceivePasswordOutput;
  },
});


