// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import SendLoginCode from "./send_login_code_type";
import ReceiveLoginCode from "./receive_login_code_type";
import VerifyLoginCode from "./verify_login_code_type";
import ReceivePassword from "./receive_password_type";
import VerifyPassword from "./verify_password_type";
import GenerateQrCode from "./generate_qr_code_type";
import DisplayMessage from "./display_message_type";


// The tagged union or sum type for the algebraic type `TaskPayload`.
const TaskPayload = __t.enum("TaskPayload", {get SendLoginCode() {
    return SendLoginCode;
  },
  get ReceiveLoginCode() {
    return ReceiveLoginCode;
  },
  get VerifyLoginCode() {
    return VerifyLoginCode;
  },
  get ReceivePassword() {
    return ReceivePassword;
  },
  get VerifyPassword() {
    return VerifyPassword;
  },
  get GenerateQrCode() {
    return GenerateQrCode;
  },
  get DisplayMessage() {
    return DisplayMessage;
  },
});

export default TaskPayload;


