[package]
name = "crm-chat-app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "crm_chat_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2.0", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1"
specta = "=2.0.0-rc.22"
specta-typescript = "0.0.9"
tauri-specta = { version = "=2.0.0-rc.21", features = ["derive", "typescript"] }
rig-core = { git = "https://github.com/0xPlaygrounds/rig.git", features = ["derive"] }
rig-surrealdb = { git = "https://github.com/0xPlaygrounds/rig.git" }
rig-qdrant = { git = "https://github.com/0xPlaygrounds/rig.git" }
surrealdb =  { version ="2.3.10", features = ["kv-surrealkv", "protocol-http", "kv-rocksdb"] }
tokio = { version = "1.48.0", features = ["sync"] }
anyhow = "1.0.100"
qdrant-client = "1.15.0"
thiserror = "2.0.17"
chat-types = { path = "../../../libs/chat-types" }
futures = "0.3"
