# Doesn't work in the sandbox
[advisories]
ignore = [
  # protobuf
  "RUSTSEC-2024-0437",
  # rsa: Marvin Attack (no fix available, used only in dev-dependencies for test keypair generation)
  "RUSTSEC-2023-0071",
]

[yanked]
enabled = false  # Warn for yanked crates in Cargo.lock (default: true)
update_index = false  # Auto-update the crates.io index (default: true)
