[package]
name = "telegram-subscriber"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
anyhow = "1.0.100"
dirs = "6"
futures = "0.3"
grammers-tl-types = { git = "https://github.com/Lonami/grammers", rev = "b595a8c4fdfa5c3a8abcb5766c959ecfe30e9f6e", features = ["impl-serde"] }
messanger-interface = { path = "../../libs/messanger-interface" }
messanger-telegram = { path = "../../libs/messanger-telegram" }
sdb_api = { path = "../../libs/sdb_api" }
sentry = { version = "0.38", default-features = false, features = ["backtrace", "contexts", "panic", "tracing", "reqwest", "rustls"] }
sentry-tracing = "0.38"
serde_json = "1.0.145"
spacetimedb-sdk = "=1.10.0"
thiserror = "2"
tokio = { version = "1.49.0", features = ["full", "macros", "rt-multi-thread"] }
tokio-util = "0.7.18"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
