[package]
name = "telegram-subscriber"
version = "0.1.0"
edition = "2024"

[dependencies]
sdb_api = { path = "../../libs/sdb_api" }
messanger-telegram = { path = "../../libs/messanger-telegram" }
spacetimedb-sdk = "1.10.*"
tokio = { version = "1.49.0", features = ["full", "macros", "rt-multi-thread"] }
anyhow = "1.0.100"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
reqwest = { version = "0.12", features = ["json"] }
jsonwebtoken = "9.3"
chrono = { version = "0.4", features = ["serde"] }
grammers-client = { git = "https://github.com/Lonami/grammers" }
grammers-session = { git = "https://github.com/Lonami/grammers" }
grammers-mtsender = { git = "https://github.com/Lonami/grammers" }
dirs = "6"