/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthDownloadsRouteImport } from './routes/_auth/downloads'
import { Route as AuthContactsRouteImport } from './routes/_auth/contacts'
import { Route as AuthChatsRouteImport } from './routes/_auth/chats'
import { Route as AuthContactsContactIdRouteImport } from './routes/_auth/contacts.$contactId'
import { Route as AuthClientClientIdRouteImport } from './routes/_auth/client.$clientId'
import { Route as AuthChatsChatIdRouteImport } from './routes/_auth/chats.$chatId'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDownloadsRoute = AuthDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => AuthRoute,
} as any)
const AuthContactsRoute = AuthContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthRoute,
} as any)
const AuthChatsRoute = AuthChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AuthRoute,
} as any)
const AuthContactsContactIdRoute = AuthContactsContactIdRouteImport.update({
  id: '/$contactId',
  path: '/$contactId',
  getParentRoute: () => AuthContactsRoute,
} as any)
const AuthClientClientIdRoute = AuthClientClientIdRouteImport.update({
  id: '/client/$clientId',
  path: '/client/$clientId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthChatsChatIdRoute = AuthChatsChatIdRouteImport.update({
  id: '/$chatId',
  path: '/$chatId',
  getParentRoute: () => AuthChatsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/chats': typeof AuthChatsRouteWithChildren
  '/contacts': typeof AuthContactsRouteWithChildren
  '/downloads': typeof AuthDownloadsRoute
  '/settings': typeof AuthSettingsRoute
  '/chats/$chatId': typeof AuthChatsChatIdRoute
  '/client/$clientId': typeof AuthClientClientIdRoute
  '/contacts/$contactId': typeof AuthContactsContactIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/chats': typeof AuthChatsRouteWithChildren
  '/contacts': typeof AuthContactsRouteWithChildren
  '/downloads': typeof AuthDownloadsRoute
  '/settings': typeof AuthSettingsRoute
  '/chats/$chatId': typeof AuthChatsChatIdRoute
  '/client/$clientId': typeof AuthClientClientIdRoute
  '/contacts/$contactId': typeof AuthContactsContactIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_auth/chats': typeof AuthChatsRouteWithChildren
  '/_auth/contacts': typeof AuthContactsRouteWithChildren
  '/_auth/downloads': typeof AuthDownloadsRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/_auth/chats/$chatId': typeof AuthChatsChatIdRoute
  '/_auth/client/$clientId': typeof AuthClientClientIdRoute
  '/_auth/contacts/$contactId': typeof AuthContactsContactIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/chats'
    | '/contacts'
    | '/downloads'
    | '/settings'
    | '/chats/$chatId'
    | '/client/$clientId'
    | '/contacts/$contactId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/chats'
    | '/contacts'
    | '/downloads'
    | '/settings'
    | '/chats/$chatId'
    | '/client/$clientId'
    | '/contacts/$contactId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/sign-in'
    | '/_auth/chats'
    | '/_auth/contacts'
    | '/_auth/downloads'
    | '/_auth/settings'
    | '/_auth/chats/$chatId'
    | '/_auth/client/$clientId'
    | '/_auth/contacts/$contactId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/downloads': {
      id: '/_auth/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof AuthDownloadsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/contacts': {
      id: '/_auth/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthContactsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/chats': {
      id: '/_auth/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthChatsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/contacts/$contactId': {
      id: '/_auth/contacts/$contactId'
      path: '/$contactId'
      fullPath: '/contacts/$contactId'
      preLoaderRoute: typeof AuthContactsContactIdRouteImport
      parentRoute: typeof AuthContactsRoute
    }
    '/_auth/client/$clientId': {
      id: '/_auth/client/$clientId'
      path: '/client/$clientId'
      fullPath: '/client/$clientId'
      preLoaderRoute: typeof AuthClientClientIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/chats/$chatId': {
      id: '/_auth/chats/$chatId'
      path: '/$chatId'
      fullPath: '/chats/$chatId'
      preLoaderRoute: typeof AuthChatsChatIdRouteImport
      parentRoute: typeof AuthChatsRoute
    }
  }
}

interface AuthChatsRouteChildren {
  AuthChatsChatIdRoute: typeof AuthChatsChatIdRoute
}

const AuthChatsRouteChildren: AuthChatsRouteChildren = {
  AuthChatsChatIdRoute: AuthChatsChatIdRoute,
}

const AuthChatsRouteWithChildren = AuthChatsRoute._addFileChildren(
  AuthChatsRouteChildren,
)

interface AuthContactsRouteChildren {
  AuthContactsContactIdRoute: typeof AuthContactsContactIdRoute
}

const AuthContactsRouteChildren: AuthContactsRouteChildren = {
  AuthContactsContactIdRoute: AuthContactsContactIdRoute,
}

const AuthContactsRouteWithChildren = AuthContactsRoute._addFileChildren(
  AuthContactsRouteChildren,
)

interface AuthRouteChildren {
  AuthChatsRoute: typeof AuthChatsRouteWithChildren
  AuthContactsRoute: typeof AuthContactsRouteWithChildren
  AuthDownloadsRoute: typeof AuthDownloadsRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthClientClientIdRoute: typeof AuthClientClientIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthChatsRoute: AuthChatsRouteWithChildren,
  AuthContactsRoute: AuthContactsRouteWithChildren,
  AuthDownloadsRoute: AuthDownloadsRoute,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthClientClientIdRoute: AuthClientClientIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
