/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthChatsRouteImport } from './routes/_auth/chats'
import { Route as AuthChatsChatIdRouteImport } from './routes/_auth/chats.$chatId'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthChatsRoute = AuthChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AuthRoute,
} as any)
const AuthChatsChatIdRoute = AuthChatsChatIdRouteImport.update({
  id: '/$chatId',
  path: '/$chatId',
  getParentRoute: () => AuthChatsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chats': typeof AuthChatsRouteWithChildren
  '/settings': typeof AuthSettingsRoute
  '/chats/$chatId': typeof AuthChatsChatIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chats': typeof AuthChatsRouteWithChildren
  '/settings': typeof AuthSettingsRoute
  '/chats/$chatId': typeof AuthChatsChatIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/chats': typeof AuthChatsRouteWithChildren
  '/_auth/settings': typeof AuthSettingsRoute
  '/_auth/chats/$chatId': typeof AuthChatsChatIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chats' | '/settings' | '/chats/$chatId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chats' | '/settings' | '/chats/$chatId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_auth/chats'
    | '/_auth/settings'
    | '/_auth/chats/$chatId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/chats': {
      id: '/_auth/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthChatsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/chats/$chatId': {
      id: '/_auth/chats/$chatId'
      path: '/$chatId'
      fullPath: '/chats/$chatId'
      preLoaderRoute: typeof AuthChatsChatIdRouteImport
      parentRoute: typeof AuthChatsRoute
    }
  }
}

interface AuthChatsRouteChildren {
  AuthChatsChatIdRoute: typeof AuthChatsChatIdRoute
}

const AuthChatsRouteChildren: AuthChatsRouteChildren = {
  AuthChatsChatIdRoute: AuthChatsChatIdRoute,
}

const AuthChatsRouteWithChildren = AuthChatsRoute._addFileChildren(
  AuthChatsRouteChildren,
)

interface AuthRouteChildren {
  AuthChatsRoute: typeof AuthChatsRouteWithChildren
  AuthSettingsRoute: typeof AuthSettingsRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthChatsRoute: AuthChatsRouteWithChildren,
  AuthSettingsRoute: AuthSettingsRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
