// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::message_type::Message;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AddMessagesArgs {
    pub messages: Vec<Message>,
}

impl From<AddMessagesArgs> for super::Reducer {
    fn from(args: AddMessagesArgs) -> Self {
        Self::AddMessages {
            messages: args.messages,
        }
    }
}

impl __sdk::InModule for AddMessagesArgs {
    type Module = super::RemoteModule;
}

pub struct AddMessagesCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `add_messages`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait add_messages {
    /// Request that the remote module invoke the reducer `add_messages` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_add_messages`] callbacks.
    fn add_messages(&self, messages: Vec<Message>) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `add_messages`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`AddMessagesCallbackId`] can be passed to [`Self::remove_on_add_messages`]
    /// to cancel the callback.
    fn on_add_messages(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &Vec<Message>) + Send + 'static,
    ) -> AddMessagesCallbackId;
    /// Cancel a callback previously registered by [`Self::on_add_messages`],
    /// causing it not to run in the future.
    fn remove_on_add_messages(&self, callback: AddMessagesCallbackId);
}

impl add_messages for super::RemoteReducers {
    fn add_messages(&self, messages: Vec<Message>) -> __sdk::Result<()> {
        self.imp
            .call_reducer("add_messages", AddMessagesArgs { messages })
    }
    fn on_add_messages(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &Vec<Message>) + Send + 'static,
    ) -> AddMessagesCallbackId {
        AddMessagesCallbackId(self.imp.on_reducer(
            "add_messages",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::AddMessages { messages },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, messages)
            }),
        ))
    }
    fn remove_on_add_messages(&self, callback: AddMessagesCallbackId) {
        self.imp.remove_on_reducer("add_messages", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `add_messages`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_add_messages {
    /// Set the call-reducer flags for the reducer `add_messages` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn add_messages(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_add_messages for super::SetReducerFlags {
    fn add_messages(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("add_messages", flags);
    }
}
