// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AssignTaskArgs {
    pub task_id: String,
}

impl From<AssignTaskArgs> for super::Reducer {
    fn from(args: AssignTaskArgs) -> Self {
        Self::AssignTask {
            task_id: args.task_id,
        }
    }
}

impl __sdk::InModule for AssignTaskArgs {
    type Module = super::RemoteModule;
}

pub struct AssignTaskCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `assign_task`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait assign_task {
    /// Request that the remote module invoke the reducer `assign_task` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_assign_task`] callbacks.
    fn assign_task(&self, task_id: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `assign_task`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`AssignTaskCallbackId`] can be passed to [`Self::remove_on_assign_task`]
    /// to cancel the callback.
    fn on_assign_task(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> AssignTaskCallbackId;
    /// Cancel a callback previously registered by [`Self::on_assign_task`],
    /// causing it not to run in the future.
    fn remove_on_assign_task(&self, callback: AssignTaskCallbackId);
}

impl assign_task for super::RemoteReducers {
    fn assign_task(&self, task_id: String) -> __sdk::Result<()> {
        self.imp
            .call_reducer("assign_task", AssignTaskArgs { task_id })
    }
    fn on_assign_task(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> AssignTaskCallbackId {
        AssignTaskCallbackId(self.imp.on_reducer(
            "assign_task",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::AssignTask { task_id },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, task_id)
            }),
        ))
    }
    fn remove_on_assign_task(&self, callback: AssignTaskCallbackId) {
        self.imp.remove_on_reducer("assign_task", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `assign_task`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_assign_task {
    /// Set the call-reducer flags for the reducer `assign_task` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn assign_task(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_assign_task for super::SetReducerFlags {
    fn assign_task(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("assign_task", flags);
    }
}
