// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::board_user_type::BoardUser;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `board_user`.
///
/// Obtain a handle from the [`BoardUserTableAccess::board_user`] method on [`super::RemoteTables`],
/// like `ctx.db.board_user()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.board_user().on_insert(...)`.
pub struct BoardUserTableHandle<'ctx> {
    imp: __sdk::TableHandle<BoardUser>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `board_user`.
///
/// Implemented for [`super::RemoteTables`].
pub trait BoardUserTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`BoardUserTableHandle`], which mediates access to the table `board_user`.
    fn board_user(&self) -> BoardUserTableHandle<'_>;
}

impl BoardUserTableAccess for super::RemoteTables {
    fn board_user(&self) -> BoardUserTableHandle<'_> {
        BoardUserTableHandle {
            imp: self.imp.get_table::<BoardUser>("board_user"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct BoardUserInsertCallbackId(__sdk::CallbackId);
pub struct BoardUserDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for BoardUserTableHandle<'ctx> {
    type Row = BoardUser;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = BoardUser> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = BoardUserInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BoardUserInsertCallbackId {
        BoardUserInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BoardUserInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = BoardUserDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BoardUserDeleteCallbackId {
        BoardUserDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BoardUserDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<BoardUser>("board_user");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct BoardUserUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for BoardUserTableHandle<'ctx> {
    type UpdateCallbackId = BoardUserUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> BoardUserUpdateCallbackId {
        BoardUserUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: BoardUserUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<BoardUser>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<BoardUser>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `board_user`,
/// which allows point queries on the field of the same name
/// via the [`BoardUserIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.board_user().id().find(...)`.
pub struct BoardUserIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<BoardUser, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> BoardUserTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `board_user`.
    pub fn id(&self) -> BoardUserIdUnique<'ctx> {
        BoardUserIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> BoardUserIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<BoardUser> {
        self.imp.find(col_val)
    }
}
