// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::board_type::Board;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `board`.
///
/// Obtain a handle from the [`BoardTableAccess::board`] method on [`super::RemoteTables`],
/// like `ctx.db.board()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.board().on_insert(...)`.
pub struct BoardTableHandle<'ctx> {
    imp: __sdk::TableHandle<Board>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `board`.
///
/// Implemented for [`super::RemoteTables`].
pub trait BoardTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`BoardTableHandle`], which mediates access to the table `board`.
    fn board(&self) -> BoardTableHandle<'_>;
}

impl BoardTableAccess for super::RemoteTables {
    fn board(&self) -> BoardTableHandle<'_> {
        BoardTableHandle {
            imp: self.imp.get_table::<Board>("board"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct BoardInsertCallbackId(__sdk::CallbackId);
pub struct BoardDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for BoardTableHandle<'ctx> {
    type Row = Board;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Board> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = BoardInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BoardInsertCallbackId {
        BoardInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BoardInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = BoardDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BoardDeleteCallbackId {
        BoardDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BoardDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Board>("board");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct BoardUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for BoardTableHandle<'ctx> {
    type UpdateCallbackId = BoardUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> BoardUpdateCallbackId {
        BoardUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: BoardUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Board>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Board>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `board`,
/// which allows point queries on the field of the same name
/// via the [`BoardIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.board().id().find(...)`.
pub struct BoardIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Board, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> BoardTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `board`.
    pub fn id(&self) -> BoardIdUnique<'ctx> {
        BoardIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> BoardIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Board> {
        self.imp.find(col_val)
    }
}
