// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::chat_type_type::ChatType;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Chat {
    pub id: u64,
    pub owner_user_id: __sdk::Identity,
    pub client_id: u64,
    pub chat_type: ChatType,
    pub external_chat_id: String,
    pub is_pinned: bool,
    pub pinned_name: Option<String>,
    pub last_message_ts: u64,
}

impl __sdk::InModule for Chat {
    type Module = super::RemoteModule;
}
