// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::chat_type::Chat;
use super::chat_type_type::ChatType;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `chat`.
///
/// Obtain a handle from the [`ChatTableAccess::chat`] method on [`super::RemoteTables`],
/// like `ctx.db.chat()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.chat().on_insert(...)`.
pub struct ChatTableHandle<'ctx> {
    imp: __sdk::TableHandle<Chat>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `chat`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ChatTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ChatTableHandle`], which mediates access to the table `chat`.
    fn chat(&self) -> ChatTableHandle<'_>;
}

impl ChatTableAccess for super::RemoteTables {
    fn chat(&self) -> ChatTableHandle<'_> {
        ChatTableHandle {
            imp: self.imp.get_table::<Chat>("chat"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ChatInsertCallbackId(__sdk::CallbackId);
pub struct ChatDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ChatTableHandle<'ctx> {
    type Row = Chat;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Chat> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ChatInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ChatInsertCallbackId {
        ChatInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ChatInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ChatDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ChatDeleteCallbackId {
        ChatDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ChatDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Chat>("chat");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct ChatUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ChatTableHandle<'ctx> {
    type UpdateCallbackId = ChatUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ChatUpdateCallbackId {
        ChatUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ChatUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Chat>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Chat>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `chat`,
/// which allows point queries on the field of the same name
/// via the [`ChatIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.chat().id().find(...)`.
pub struct ChatIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Chat, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ChatTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `chat`.
    pub fn id(&self) -> ChatIdUnique<'ctx> {
        ChatIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ChatIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Chat> {
        self.imp.find(col_val)
    }
}
