// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DeleteClientArgs {
    pub client_id: u64,
}

impl From<DeleteClientArgs> for super::Reducer {
    fn from(args: DeleteClientArgs) -> Self {
        Self::DeleteClient {
            client_id: args.client_id,
        }
    }
}

impl __sdk::InModule for DeleteClientArgs {
    type Module = super::RemoteModule;
}

pub struct DeleteClientCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `delete_client`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait delete_client {
    /// Request that the remote module invoke the reducer `delete_client` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_delete_client`] callbacks.
    fn delete_client(&self, client_id: u64) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `delete_client`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`DeleteClientCallbackId`] can be passed to [`Self::remove_on_delete_client`]
    /// to cancel the callback.
    fn on_delete_client(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64) + Send + 'static,
    ) -> DeleteClientCallbackId;
    /// Cancel a callback previously registered by [`Self::on_delete_client`],
    /// causing it not to run in the future.
    fn remove_on_delete_client(&self, callback: DeleteClientCallbackId);
}

impl delete_client for super::RemoteReducers {
    fn delete_client(&self, client_id: u64) -> __sdk::Result<()> {
        self.imp
            .call_reducer("delete_client", DeleteClientArgs { client_id })
    }
    fn on_delete_client(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64) + Send + 'static,
    ) -> DeleteClientCallbackId {
        DeleteClientCallbackId(self.imp.on_reducer(
            "delete_client",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::DeleteClient { client_id },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, client_id)
            }),
        ))
    }
    fn remove_on_delete_client(&self, callback: DeleteClientCallbackId) {
        self.imp.remove_on_reducer("delete_client", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `delete_client`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_delete_client {
    /// Set the call-reducer flags for the reducer `delete_client` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn delete_client(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_delete_client for super::SetReducerFlags {
    fn delete_client(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("delete_client", flags);
    }
}
