// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DeleteChatArgs {
    pub chat_id: u64,
}

impl From<DeleteChatArgs> for super::Reducer {
    fn from(args: DeleteChatArgs) -> Self {
        Self::DeleteChat {
            chat_id: args.chat_id,
        }
    }
}

impl __sdk::InModule for DeleteChatArgs {
    type Module = super::RemoteModule;
}

pub struct DeleteChatCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `delete_chat`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait delete_chat {
    /// Request that the remote module invoke the reducer `delete_chat` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_delete_chat`] callbacks.
    fn delete_chat(&self, chat_id: u64) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `delete_chat`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`DeleteChatCallbackId`] can be passed to [`Self::remove_on_delete_chat`]
    /// to cancel the callback.
    fn on_delete_chat(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64) + Send + 'static,
    ) -> DeleteChatCallbackId;
    /// Cancel a callback previously registered by [`Self::on_delete_chat`],
    /// causing it not to run in the future.
    fn remove_on_delete_chat(&self, callback: DeleteChatCallbackId);
}

impl delete_chat for super::RemoteReducers {
    fn delete_chat(&self, chat_id: u64) -> __sdk::Result<()> {
        self.imp
            .call_reducer("delete_chat", DeleteChatArgs { chat_id })
    }
    fn on_delete_chat(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64) + Send + 'static,
    ) -> DeleteChatCallbackId {
        DeleteChatCallbackId(self.imp.on_reducer(
            "delete_chat",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::DeleteChat { chat_id },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, chat_id)
            }),
        ))
    }
    fn remove_on_delete_chat(&self, callback: DeleteChatCallbackId) {
        self.imp.remove_on_reducer("delete_chat", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `delete_chat`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_delete_chat {
    /// Set the call-reducer flags for the reducer `delete_chat` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn delete_chat(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_delete_chat for super::SetReducerFlags {
    fn delete_chat(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("delete_chat", flags);
    }
}
