// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DismissNotificationArgs {
    pub notification_id: u64,
}

impl From<DismissNotificationArgs> for super::Reducer {
    fn from(args: DismissNotificationArgs) -> Self {
        Self::DismissNotification {
            notification_id: args.notification_id,
        }
    }
}

impl __sdk::InModule for DismissNotificationArgs {
    type Module = super::RemoteModule;
}

pub struct DismissNotificationCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `dismiss_notification`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait dismiss_notification {
    /// Request that the remote module invoke the reducer `dismiss_notification` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_dismiss_notification`] callbacks.
    fn dismiss_notification(&self, notification_id: u64) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `dismiss_notification`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`DismissNotificationCallbackId`] can be passed to [`Self::remove_on_dismiss_notification`]
    /// to cancel the callback.
    fn on_dismiss_notification(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64) + Send + 'static,
    ) -> DismissNotificationCallbackId;
    /// Cancel a callback previously registered by [`Self::on_dismiss_notification`],
    /// causing it not to run in the future.
    fn remove_on_dismiss_notification(&self, callback: DismissNotificationCallbackId);
}

impl dismiss_notification for super::RemoteReducers {
    fn dismiss_notification(&self, notification_id: u64) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "dismiss_notification",
            DismissNotificationArgs { notification_id },
        )
    }
    fn on_dismiss_notification(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64) + Send + 'static,
    ) -> DismissNotificationCallbackId {
        DismissNotificationCallbackId(self.imp.on_reducer(
            "dismiss_notification",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::DismissNotification { notification_id },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, notification_id)
            }),
        ))
    }
    fn remove_on_dismiss_notification(&self, callback: DismissNotificationCallbackId) {
        self.imp
            .remove_on_reducer("dismiss_notification", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `dismiss_notification`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_dismiss_notification {
    /// Set the call-reducer flags for the reducer `dismiss_notification` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn dismiss_notification(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_dismiss_notification for super::SetReducerFlags {
    fn dismiss_notification(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("dismiss_notification", flags);
    }
}
