// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::qr_token_type::QrToken;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub enum GenerateQrCodeOutput {
    Pending,

    Token(QrToken),

    AlreadyAuthorized,

    Failed(String),
}

impl __sdk::InModule for GenerateQrCodeOutput {
    type Module = super::RemoteModule;
}
