// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::human_type::Human;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `human`.
///
/// Obtain a handle from the [`HumanTableAccess::human`] method on [`super::RemoteTables`],
/// like `ctx.db.human()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.human().on_insert(...)`.
pub struct HumanTableHandle<'ctx> {
    imp: __sdk::TableHandle<Human>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `human`.
///
/// Implemented for [`super::RemoteTables`].
pub trait HumanTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`HumanTableHandle`], which mediates access to the table `human`.
    fn human(&self) -> HumanTableHandle<'_>;
}

impl HumanTableAccess for super::RemoteTables {
    fn human(&self) -> HumanTableHandle<'_> {
        HumanTableHandle {
            imp: self.imp.get_table::<Human>("human"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct HumanInsertCallbackId(__sdk::CallbackId);
pub struct HumanDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for HumanTableHandle<'ctx> {
    type Row = Human;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Human> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = HumanInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> HumanInsertCallbackId {
        HumanInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: HumanInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = HumanDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> HumanDeleteCallbackId {
        HumanDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: HumanDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Human>("human");
    _table.add_unique_constraint::<__sdk::Identity>("id", |row| &row.id);
}
pub struct HumanUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for HumanTableHandle<'ctx> {
    type UpdateCallbackId = HumanUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> HumanUpdateCallbackId {
        HumanUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: HumanUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Human>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Human>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `human`,
/// which allows point queries on the field of the same name
/// via the [`HumanIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.human().id().find(...)`.
pub struct HumanIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Human, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> HumanTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `human`.
    pub fn id(&self) -> HumanIdUnique<'ctx> {
        HumanIdUnique {
            imp: self.imp.get_unique_constraint::<__sdk::Identity>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> HumanIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<Human> {
        self.imp.find(col_val)
    }
}
