// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct MarkMessageDeletedArgs {
    pub external_message_id: String,
}

impl From<MarkMessageDeletedArgs> for super::Reducer {
    fn from(args: MarkMessageDeletedArgs) -> Self {
        Self::MarkMessageDeleted {
            external_message_id: args.external_message_id,
        }
    }
}

impl __sdk::InModule for MarkMessageDeletedArgs {
    type Module = super::RemoteModule;
}

pub struct MarkMessageDeletedCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `mark_message_deleted`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait mark_message_deleted {
    /// Request that the remote module invoke the reducer `mark_message_deleted` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_mark_message_deleted`] callbacks.
    fn mark_message_deleted(&self, external_message_id: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `mark_message_deleted`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`MarkMessageDeletedCallbackId`] can be passed to [`Self::remove_on_mark_message_deleted`]
    /// to cancel the callback.
    fn on_mark_message_deleted(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> MarkMessageDeletedCallbackId;
    /// Cancel a callback previously registered by [`Self::on_mark_message_deleted`],
    /// causing it not to run in the future.
    fn remove_on_mark_message_deleted(&self, callback: MarkMessageDeletedCallbackId);
}

impl mark_message_deleted for super::RemoteReducers {
    fn mark_message_deleted(&self, external_message_id: String) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "mark_message_deleted",
            MarkMessageDeletedArgs {
                external_message_id,
            },
        )
    }
    fn on_mark_message_deleted(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> MarkMessageDeletedCallbackId {
        MarkMessageDeletedCallbackId(self.imp.on_reducer(
            "mark_message_deleted",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::MarkMessageDeleted {
                                    external_message_id,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, external_message_id)
            }),
        ))
    }
    fn remove_on_mark_message_deleted(&self, callback: MarkMessageDeletedCallbackId) {
        self.imp
            .remove_on_reducer("mark_message_deleted", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `mark_message_deleted`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_mark_message_deleted {
    /// Set the call-reducer flags for the reducer `mark_message_deleted` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn mark_message_deleted(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_mark_message_deleted for super::SetReducerFlags {
    fn mark_message_deleted(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("mark_message_deleted", flags);
    }
}
