// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::media_kind_type::MediaKind;
use super::media_type::Media;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `media`.
///
/// Obtain a handle from the [`MediaTableAccess::media`] method on [`super::RemoteTables`],
/// like `ctx.db.media()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.media().on_insert(...)`.
pub struct MediaTableHandle<'ctx> {
    imp: __sdk::TableHandle<Media>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `media`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MediaTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MediaTableHandle`], which mediates access to the table `media`.
    fn media(&self) -> MediaTableHandle<'_>;
}

impl MediaTableAccess for super::RemoteTables {
    fn media(&self) -> MediaTableHandle<'_> {
        MediaTableHandle {
            imp: self.imp.get_table::<Media>("media"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MediaInsertCallbackId(__sdk::CallbackId);
pub struct MediaDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MediaTableHandle<'ctx> {
    type Row = Media;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Media> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MediaInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MediaInsertCallbackId {
        MediaInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MediaInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MediaDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MediaDeleteCallbackId {
        MediaDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MediaDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Media>("media");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct MediaUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MediaTableHandle<'ctx> {
    type UpdateCallbackId = MediaUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MediaUpdateCallbackId {
        MediaUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MediaUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Media>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Media>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `media`,
/// which allows point queries on the field of the same name
/// via the [`MediaIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.media().id().find(...)`.
pub struct MediaIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Media, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> MediaTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `media`.
    pub fn id(&self) -> MediaIdUnique<'ctx> {
        MediaIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> MediaIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Media> {
        self.imp.find(col_val)
    }
}
