// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Message {
    pub id: String,
    pub external_id: String,
    pub owner_user_id: __sdk::Identity,
    pub client_id: u64,
    pub chat_id: String,
    pub sender_id: String,
    pub text: Option<String>,
    pub out: bool,
    pub deleted: bool,
    pub ts: u64,
    pub media_id: Option<u64>,
}

impl __sdk::InModule for Message {
    type Module = super::RemoteModule;
}
