// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.10.0 (commit 1d576dc75ca066879f6d9ee4d156c5bce940bd31).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

pub mod cancel_phone_auth_reducer;
pub mod cancel_qr_auth_reducer;
pub mod chat_table;
pub mod chat_type;
pub mod chat_type_type;
pub mod client_connected_reducer;
pub mod client_kind_type;
pub mod client_status_type;
pub mod client_table;
pub mod client_type;
pub mod delete_chat_reducer;
pub mod delete_client_reducer;
pub mod dismiss_notification_reducer;
pub mod human_table;
pub mod human_type;
pub mod identity_disconnected_reducer;
pub mod mark_message_deleted_reducer;
pub mod message_severity_type;
pub mod message_table;
pub mod message_type;
pub mod notification_table;
pub mod notification_type;
pub mod password_required_info_type;
pub mod phone_auth_step_type;
pub mod phone_auth_table;
pub mod phone_auth_type;
pub mod qr_auth_result_type;
pub mod qr_auth_step_type;
pub mod qr_auth_table;
pub mod qr_auth_type;
pub mod robot_claim_phone_auth_reducer;
pub mod robot_claim_qr_auth_reducer;
pub mod robot_complete_qr_auth_reducer;
pub mod robot_complete_send_code_reducer;
pub mod robot_complete_verify_code_reducer;
pub mod robot_complete_verify_password_reducer;
pub mod robot_table;
pub mod robot_type;
pub mod robot_update_qr_token_reducer;
pub mod send_code_result_type;
pub mod send_code_success_type;
pub mod start_phone_auth_reducer;
pub mod start_qr_auth_reducer;
pub mod submit_login_code_reducer;
pub mod submit_password_reducer;
pub mod upsert_chat_reducer;
pub mod upsert_message_reducer;
pub mod verify_code_result_type;
pub mod verify_code_success_type;
pub mod verify_password_result_type;
pub mod verify_password_success_type;

pub use cancel_phone_auth_reducer::{
    CancelPhoneAuthCallbackId, cancel_phone_auth, set_flags_for_cancel_phone_auth,
};
pub use cancel_qr_auth_reducer::{
    CancelQrAuthCallbackId, cancel_qr_auth, set_flags_for_cancel_qr_auth,
};
pub use chat_table::*;
pub use chat_type::Chat;
pub use chat_type_type::ChatType;
pub use client_connected_reducer::{
    ClientConnectedCallbackId, client_connected, set_flags_for_client_connected,
};
pub use client_kind_type::ClientKind;
pub use client_status_type::ClientStatus;
pub use client_table::*;
pub use client_type::Client;
pub use delete_chat_reducer::{DeleteChatCallbackId, delete_chat, set_flags_for_delete_chat};
pub use delete_client_reducer::{
    DeleteClientCallbackId, delete_client, set_flags_for_delete_client,
};
pub use dismiss_notification_reducer::{
    DismissNotificationCallbackId, dismiss_notification, set_flags_for_dismiss_notification,
};
pub use human_table::*;
pub use human_type::Human;
pub use identity_disconnected_reducer::{
    IdentityDisconnectedCallbackId, identity_disconnected, set_flags_for_identity_disconnected,
};
pub use mark_message_deleted_reducer::{
    MarkMessageDeletedCallbackId, mark_message_deleted, set_flags_for_mark_message_deleted,
};
pub use message_severity_type::MessageSeverity;
pub use message_table::*;
pub use message_type::Message;
pub use notification_table::*;
pub use notification_type::Notification;
pub use password_required_info_type::PasswordRequiredInfo;
pub use phone_auth_step_type::PhoneAuthStep;
pub use phone_auth_table::*;
pub use phone_auth_type::PhoneAuth;
pub use qr_auth_result_type::QrAuthResult;
pub use qr_auth_step_type::QrAuthStep;
pub use qr_auth_table::*;
pub use qr_auth_type::QrAuth;
pub use robot_claim_phone_auth_reducer::{
    RobotClaimPhoneAuthCallbackId, robot_claim_phone_auth, set_flags_for_robot_claim_phone_auth,
};
pub use robot_claim_qr_auth_reducer::{
    RobotClaimQrAuthCallbackId, robot_claim_qr_auth, set_flags_for_robot_claim_qr_auth,
};
pub use robot_complete_qr_auth_reducer::{
    RobotCompleteQrAuthCallbackId, robot_complete_qr_auth, set_flags_for_robot_complete_qr_auth,
};
pub use robot_complete_send_code_reducer::{
    RobotCompleteSendCodeCallbackId, robot_complete_send_code,
    set_flags_for_robot_complete_send_code,
};
pub use robot_complete_verify_code_reducer::{
    RobotCompleteVerifyCodeCallbackId, robot_complete_verify_code,
    set_flags_for_robot_complete_verify_code,
};
pub use robot_complete_verify_password_reducer::{
    RobotCompleteVerifyPasswordCallbackId, robot_complete_verify_password,
    set_flags_for_robot_complete_verify_password,
};
pub use robot_table::*;
pub use robot_type::Robot;
pub use robot_update_qr_token_reducer::{
    RobotUpdateQrTokenCallbackId, robot_update_qr_token, set_flags_for_robot_update_qr_token,
};
pub use send_code_result_type::SendCodeResult;
pub use send_code_success_type::SendCodeSuccess;
pub use start_phone_auth_reducer::{
    StartPhoneAuthCallbackId, set_flags_for_start_phone_auth, start_phone_auth,
};
pub use start_qr_auth_reducer::{
    StartQrAuthCallbackId, set_flags_for_start_qr_auth, start_qr_auth,
};
pub use submit_login_code_reducer::{
    SubmitLoginCodeCallbackId, set_flags_for_submit_login_code, submit_login_code,
};
pub use submit_password_reducer::{
    SubmitPasswordCallbackId, set_flags_for_submit_password, submit_password,
};
pub use upsert_chat_reducer::{UpsertChatCallbackId, set_flags_for_upsert_chat, upsert_chat};
pub use upsert_message_reducer::{
    UpsertMessageCallbackId, set_flags_for_upsert_message, upsert_message,
};
pub use verify_code_result_type::VerifyCodeResult;
pub use verify_code_success_type::VerifyCodeSuccess;
pub use verify_password_result_type::VerifyPasswordResult;
pub use verify_password_success_type::VerifyPasswordSuccess;

#[derive(Clone, PartialEq, Debug)]

/// One of the reducers defined by this module.
///
/// Contained within a [`__sdk::ReducerEvent`] in [`EventContext`]s for reducer events
/// to indicate which reducer caused the event.

pub enum Reducer {
    CancelPhoneAuth {
        auth_id: u64,
    },
    CancelQrAuth {
        auth_id: u64,
    },
    ClientConnected,
    DeleteChat {
        chat_id: String,
    },
    DeleteClient {
        client_id: u64,
    },
    DismissNotification {
        notification_id: u64,
    },
    IdentityDisconnected,
    MarkMessageDeleted {
        external_message_id: String,
    },
    RobotClaimPhoneAuth {
        auth_id: u64,
    },
    RobotClaimQrAuth {
        auth_id: u64,
    },
    RobotCompleteQrAuth {
        auth_id: u64,
        result: QrAuthResult,
    },
    RobotCompleteSendCode {
        auth_id: u64,
        result: SendCodeResult,
    },
    RobotCompleteVerifyCode {
        auth_id: u64,
        result: VerifyCodeResult,
    },
    RobotCompleteVerifyPassword {
        auth_id: u64,
        result: VerifyPasswordResult,
    },
    RobotUpdateQrToken {
        auth_id: u64,
        url: String,
        expires: i32,
    },
    StartPhoneAuth {
        phone: String,
    },
    StartQrAuth,
    SubmitLoginCode {
        auth_id: u64,
        code: String,
    },
    SubmitPassword {
        auth_id: u64,
        password: String,
    },
    UpsertChat {
        chat: Chat,
    },
    UpsertMessage {
        message: Message,
    },
}

impl __sdk::InModule for Reducer {
    type Module = RemoteModule;
}

impl __sdk::Reducer for Reducer {
    fn reducer_name(&self) -> &'static str {
        match self {
            Reducer::CancelPhoneAuth { .. } => "cancel_phone_auth",
            Reducer::CancelQrAuth { .. } => "cancel_qr_auth",
            Reducer::ClientConnected => "client_connected",
            Reducer::DeleteChat { .. } => "delete_chat",
            Reducer::DeleteClient { .. } => "delete_client",
            Reducer::DismissNotification { .. } => "dismiss_notification",
            Reducer::IdentityDisconnected => "identity_disconnected",
            Reducer::MarkMessageDeleted { .. } => "mark_message_deleted",
            Reducer::RobotClaimPhoneAuth { .. } => "robot_claim_phone_auth",
            Reducer::RobotClaimQrAuth { .. } => "robot_claim_qr_auth",
            Reducer::RobotCompleteQrAuth { .. } => "robot_complete_qr_auth",
            Reducer::RobotCompleteSendCode { .. } => "robot_complete_send_code",
            Reducer::RobotCompleteVerifyCode { .. } => "robot_complete_verify_code",
            Reducer::RobotCompleteVerifyPassword { .. } => "robot_complete_verify_password",
            Reducer::RobotUpdateQrToken { .. } => "robot_update_qr_token",
            Reducer::StartPhoneAuth { .. } => "start_phone_auth",
            Reducer::StartQrAuth => "start_qr_auth",
            Reducer::SubmitLoginCode { .. } => "submit_login_code",
            Reducer::SubmitPassword { .. } => "submit_password",
            Reducer::UpsertChat { .. } => "upsert_chat",
            Reducer::UpsertMessage { .. } => "upsert_message",
            _ => unreachable!(),
        }
    }
}
impl TryFrom<__ws::ReducerCallInfo<__ws::BsatnFormat>> for Reducer {
    type Error = __sdk::Error;
    fn try_from(value: __ws::ReducerCallInfo<__ws::BsatnFormat>) -> __sdk::Result<Self> {
        match &value.reducer_name[..] {
            "cancel_phone_auth" => Ok(__sdk::parse_reducer_args::<
                cancel_phone_auth_reducer::CancelPhoneAuthArgs,
            >("cancel_phone_auth", &value.args)?
            .into()),
            "cancel_qr_auth" => Ok(__sdk::parse_reducer_args::<
                cancel_qr_auth_reducer::CancelQrAuthArgs,
            >("cancel_qr_auth", &value.args)?
            .into()),
            "client_connected" => Ok(__sdk::parse_reducer_args::<
                client_connected_reducer::ClientConnectedArgs,
            >("client_connected", &value.args)?
            .into()),
            "delete_chat" => Ok(
                __sdk::parse_reducer_args::<delete_chat_reducer::DeleteChatArgs>(
                    "delete_chat",
                    &value.args,
                )?
                .into(),
            ),
            "delete_client" => Ok(__sdk::parse_reducer_args::<
                delete_client_reducer::DeleteClientArgs,
            >("delete_client", &value.args)?
            .into()),
            "dismiss_notification" => Ok(__sdk::parse_reducer_args::<
                dismiss_notification_reducer::DismissNotificationArgs,
            >("dismiss_notification", &value.args)?
            .into()),
            "identity_disconnected" => Ok(__sdk::parse_reducer_args::<
                identity_disconnected_reducer::IdentityDisconnectedArgs,
            >("identity_disconnected", &value.args)?
            .into()),
            "mark_message_deleted" => Ok(__sdk::parse_reducer_args::<
                mark_message_deleted_reducer::MarkMessageDeletedArgs,
            >("mark_message_deleted", &value.args)?
            .into()),
            "robot_claim_phone_auth" => Ok(__sdk::parse_reducer_args::<
                robot_claim_phone_auth_reducer::RobotClaimPhoneAuthArgs,
            >("robot_claim_phone_auth", &value.args)?
            .into()),
            "robot_claim_qr_auth" => Ok(__sdk::parse_reducer_args::<
                robot_claim_qr_auth_reducer::RobotClaimQrAuthArgs,
            >("robot_claim_qr_auth", &value.args)?
            .into()),
            "robot_complete_qr_auth" => Ok(__sdk::parse_reducer_args::<
                robot_complete_qr_auth_reducer::RobotCompleteQrAuthArgs,
            >("robot_complete_qr_auth", &value.args)?
            .into()),
            "robot_complete_send_code" => {
                Ok(__sdk::parse_reducer_args::<
                    robot_complete_send_code_reducer::RobotCompleteSendCodeArgs,
                >("robot_complete_send_code", &value.args)?
                .into())
            }
            "robot_complete_verify_code" => {
                Ok(__sdk::parse_reducer_args::<
                    robot_complete_verify_code_reducer::RobotCompleteVerifyCodeArgs,
                >("robot_complete_verify_code", &value.args)?
                .into())
            }
            "robot_complete_verify_password" => {
                Ok(__sdk::parse_reducer_args::<
                    robot_complete_verify_password_reducer::RobotCompleteVerifyPasswordArgs,
                >("robot_complete_verify_password", &value.args)?
                .into())
            }
            "robot_update_qr_token" => Ok(__sdk::parse_reducer_args::<
                robot_update_qr_token_reducer::RobotUpdateQrTokenArgs,
            >("robot_update_qr_token", &value.args)?
            .into()),
            "start_phone_auth" => Ok(__sdk::parse_reducer_args::<
                start_phone_auth_reducer::StartPhoneAuthArgs,
            >("start_phone_auth", &value.args)?
            .into()),
            "start_qr_auth" => Ok(__sdk::parse_reducer_args::<
                start_qr_auth_reducer::StartQrAuthArgs,
            >("start_qr_auth", &value.args)?
            .into()),
            "submit_login_code" => Ok(__sdk::parse_reducer_args::<
                submit_login_code_reducer::SubmitLoginCodeArgs,
            >("submit_login_code", &value.args)?
            .into()),
            "submit_password" => Ok(__sdk::parse_reducer_args::<
                submit_password_reducer::SubmitPasswordArgs,
            >("submit_password", &value.args)?
            .into()),
            "upsert_chat" => Ok(
                __sdk::parse_reducer_args::<upsert_chat_reducer::UpsertChatArgs>(
                    "upsert_chat",
                    &value.args,
                )?
                .into(),
            ),
            "upsert_message" => Ok(__sdk::parse_reducer_args::<
                upsert_message_reducer::UpsertMessageArgs,
            >("upsert_message", &value.args)?
            .into()),
            unknown => {
                Err(
                    __sdk::InternalError::unknown_name("reducer", unknown, "ReducerCallInfo")
                        .into(),
                )
            }
        }
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct DbUpdate {
    chat: __sdk::TableUpdate<Chat>,
    client: __sdk::TableUpdate<Client>,
    human: __sdk::TableUpdate<Human>,
    message: __sdk::TableUpdate<Message>,
    notification: __sdk::TableUpdate<Notification>,
    phone_auth: __sdk::TableUpdate<PhoneAuth>,
    qr_auth: __sdk::TableUpdate<QrAuth>,
    robot: __sdk::TableUpdate<Robot>,
}

impl TryFrom<__ws::DatabaseUpdate<__ws::BsatnFormat>> for DbUpdate {
    type Error = __sdk::Error;
    fn try_from(raw: __ws::DatabaseUpdate<__ws::BsatnFormat>) -> Result<Self, Self::Error> {
        let mut db_update = DbUpdate::default();
        for table_update in raw.tables {
            match &table_update.table_name[..] {
                "chat" => db_update
                    .chat
                    .append(chat_table::parse_table_update(table_update)?),
                "client" => db_update
                    .client
                    .append(client_table::parse_table_update(table_update)?),
                "human" => db_update
                    .human
                    .append(human_table::parse_table_update(table_update)?),
                "message" => db_update
                    .message
                    .append(message_table::parse_table_update(table_update)?),
                "notification" => db_update
                    .notification
                    .append(notification_table::parse_table_update(table_update)?),
                "phone_auth" => db_update
                    .phone_auth
                    .append(phone_auth_table::parse_table_update(table_update)?),
                "qr_auth" => db_update
                    .qr_auth
                    .append(qr_auth_table::parse_table_update(table_update)?),
                "robot" => db_update
                    .robot
                    .append(robot_table::parse_table_update(table_update)?),

                unknown => {
                    return Err(__sdk::InternalError::unknown_name(
                        "table",
                        unknown,
                        "DatabaseUpdate",
                    )
                    .into());
                }
            }
        }
        Ok(db_update)
    }
}

impl __sdk::InModule for DbUpdate {
    type Module = RemoteModule;
}

impl __sdk::DbUpdate for DbUpdate {
    fn apply_to_client_cache(
        &self,
        cache: &mut __sdk::ClientCache<RemoteModule>,
    ) -> AppliedDiff<'_> {
        let mut diff = AppliedDiff::default();

        diff.chat = cache
            .apply_diff_to_table::<Chat>("chat", &self.chat)
            .with_updates_by_pk(|row| &row.id);
        diff.client = cache
            .apply_diff_to_table::<Client>("client", &self.client)
            .with_updates_by_pk(|row| &row.id);
        diff.human = cache
            .apply_diff_to_table::<Human>("human", &self.human)
            .with_updates_by_pk(|row| &row.id);
        diff.message = cache
            .apply_diff_to_table::<Message>("message", &self.message)
            .with_updates_by_pk(|row| &row.id);
        diff.notification = cache
            .apply_diff_to_table::<Notification>("notification", &self.notification)
            .with_updates_by_pk(|row| &row.id);
        diff.phone_auth = cache
            .apply_diff_to_table::<PhoneAuth>("phone_auth", &self.phone_auth)
            .with_updates_by_pk(|row| &row.id);
        diff.qr_auth = cache
            .apply_diff_to_table::<QrAuth>("qr_auth", &self.qr_auth)
            .with_updates_by_pk(|row| &row.id);
        diff.robot = cache
            .apply_diff_to_table::<Robot>("robot", &self.robot)
            .with_updates_by_pk(|row| &row.id);

        diff
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct AppliedDiff<'r> {
    chat: __sdk::TableAppliedDiff<'r, Chat>,
    client: __sdk::TableAppliedDiff<'r, Client>,
    human: __sdk::TableAppliedDiff<'r, Human>,
    message: __sdk::TableAppliedDiff<'r, Message>,
    notification: __sdk::TableAppliedDiff<'r, Notification>,
    phone_auth: __sdk::TableAppliedDiff<'r, PhoneAuth>,
    qr_auth: __sdk::TableAppliedDiff<'r, QrAuth>,
    robot: __sdk::TableAppliedDiff<'r, Robot>,
    __unused: std::marker::PhantomData<&'r ()>,
}

impl __sdk::InModule for AppliedDiff<'_> {
    type Module = RemoteModule;
}

impl<'r> __sdk::AppliedDiff<'r> for AppliedDiff<'r> {
    fn invoke_row_callbacks(
        &self,
        event: &EventContext,
        callbacks: &mut __sdk::DbCallbacks<RemoteModule>,
    ) {
        callbacks.invoke_table_row_callbacks::<Chat>("chat", &self.chat, event);
        callbacks.invoke_table_row_callbacks::<Client>("client", &self.client, event);
        callbacks.invoke_table_row_callbacks::<Human>("human", &self.human, event);
        callbacks.invoke_table_row_callbacks::<Message>("message", &self.message, event);
        callbacks.invoke_table_row_callbacks::<Notification>(
            "notification",
            &self.notification,
            event,
        );
        callbacks.invoke_table_row_callbacks::<PhoneAuth>("phone_auth", &self.phone_auth, event);
        callbacks.invoke_table_row_callbacks::<QrAuth>("qr_auth", &self.qr_auth, event);
        callbacks.invoke_table_row_callbacks::<Robot>("robot", &self.robot, event);
    }
}

#[doc(hidden)]
pub struct RemoteModule;

impl __sdk::InModule for RemoteModule {
    type Module = Self;
}

/// The `reducers` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
pub struct RemoteReducers {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteReducers {
    type Module = RemoteModule;
}

/// The `procedures` field of [`DbConnection`] and other [`DbContext`] types,
/// with methods provided by extension traits for each procedure defined by the module.
pub struct RemoteProcedures {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteProcedures {
    type Module = RemoteModule;
}

#[doc(hidden)]
/// The `set_reducer_flags` field of [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
/// Each method sets the flags for the reducer with the same name.
///
/// This type is currently unstable and may be removed without a major version bump.
pub struct SetReducerFlags {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for SetReducerFlags {
    type Module = RemoteModule;
}

/// The `db` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each table defined by the module.
pub struct RemoteTables {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteTables {
    type Module = RemoteModule;
}

/// A connection to a remote module, including a materialized view of a subset of the database.
///
/// Connect to a remote module by calling [`DbConnection::builder`]
/// and using the [`__sdk::DbConnectionBuilder`] builder-pattern constructor.
///
/// You must explicitly advance the connection by calling any one of:
///
/// - [`DbConnection::frame_tick`].
/// - [`DbConnection::run_threaded`].
/// - [`DbConnection::run_async`].
/// - [`DbConnection::advance_one_message`].
/// - [`DbConnection::advance_one_message_blocking`].
/// - [`DbConnection::advance_one_message_async`].
///
/// Which of these methods you should call depends on the specific needs of your application,
/// but you must call one of them, or else the connection will never progress.
pub struct DbConnection {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    #[doc(hidden)]
    /// Access to setting the call-flags of each reducer defined for each reducer defined by the module
    /// via extension traits implemented for [`SetReducerFlags`].
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    pub set_reducer_flags: SetReducerFlags,

    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,

    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for DbConnection {
    type Module = RemoteModule;
}

impl __sdk::DbContext for DbConnection {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type SetReducerFlags = SetReducerFlags;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }
    fn set_reducer_flags(&self) -> &Self::SetReducerFlags {
        &self.set_reducer_flags
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl DbConnection {
    /// Builder-pattern constructor for a connection to a remote module.
    ///
    /// See [`__sdk::DbConnectionBuilder`] for required and optional configuration for the new connection.
    pub fn builder() -> __sdk::DbConnectionBuilder<RemoteModule> {
        __sdk::DbConnectionBuilder::new()
    }

    /// If any WebSocket messages are waiting, process one of them.
    ///
    /// Returns `true` if a message was processed, or `false` if the queue is empty.
    /// Callers should invoke this message in a loop until it returns `false`
    /// or for as much time is available to process messages.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::frame_tick`] each frame
    /// to fully exhaust the queue whenever time is available.
    pub fn advance_one_message(&self) -> __sdk::Result<bool> {
        self.imp.advance_one_message()
    }

    /// Process one WebSocket message, potentially blocking the current thread until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_threaded`] to spawn a thread
    /// which advances the connection automatically.
    pub fn advance_one_message_blocking(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_blocking()
    }

    /// Process one WebSocket message, `await`ing until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_async`] to run an `async` loop
    /// which advances the connection when polled.
    pub async fn advance_one_message_async(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_async().await
    }

    /// Process all WebSocket messages waiting in the queue,
    /// then return without `await`ing or blocking the current thread.
    pub fn frame_tick(&self) -> __sdk::Result<()> {
        self.imp.frame_tick()
    }

    /// Spawn a thread which processes WebSocket messages as they are received.
    pub fn run_threaded(&self) -> std::thread::JoinHandle<()> {
        self.imp.run_threaded()
    }

    /// Run an `async` loop which processes WebSocket messages when polled.
    pub async fn run_async(&self) -> __sdk::Result<()> {
        self.imp.run_async().await
    }
}

impl __sdk::DbConnection for DbConnection {
    fn new(imp: __sdk::DbContextImpl<RemoteModule>) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            set_reducer_flags: SetReducerFlags { imp: imp.clone() },
            imp,
        }
    }
}

/// A handle on a subscribed query.
// TODO: Document this better after implementing the new subscription API.
#[derive(Clone)]
pub struct SubscriptionHandle {
    imp: __sdk::SubscriptionHandleImpl<RemoteModule>,
}

impl __sdk::InModule for SubscriptionHandle {
    type Module = RemoteModule;
}

impl __sdk::SubscriptionHandle for SubscriptionHandle {
    fn new(imp: __sdk::SubscriptionHandleImpl<RemoteModule>) -> Self {
        Self { imp }
    }

    /// Returns true if this subscription has been terminated due to an unsubscribe call or an error.
    fn is_ended(&self) -> bool {
        self.imp.is_ended()
    }

    /// Returns true if this subscription has been applied and has not yet been unsubscribed.
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Unsubscribe from the query controlled by this `SubscriptionHandle`,
    /// then run `on_end` when its rows are removed from the client cache.
    fn unsubscribe_then(self, on_end: __sdk::OnEndedCallback<RemoteModule>) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(Some(on_end))
    }

    fn unsubscribe(self) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(None)
    }
}

/// Alias trait for a [`__sdk::DbContext`] connected to this module,
/// with that trait's associated types bounded to this module's concrete types.
///
/// Users can use this trait as a boundary on definitions which should accept
/// either a [`DbConnection`] or an [`EventContext`] and operate on either.
pub trait RemoteDbContext:
    __sdk::DbContext<
        DbView = RemoteTables,
        Reducers = RemoteReducers,
        SetReducerFlags = SetReducerFlags,
        SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
    >
{
}
impl<
    Ctx: __sdk::DbContext<
            DbView = RemoteTables,
            Reducers = RemoteReducers,
            SetReducerFlags = SetReducerFlags,
            SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
        >,
> RemoteDbContext for Ctx
{
}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Event`],
/// passed to [`__sdk::Table::on_insert`], [`__sdk::Table::on_delete`] and [`__sdk::TableWithPrimaryKey::on_update`] callbacks.
pub struct EventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to setting the call-flags of each reducer defined for each reducer defined by the module
    /// via extension traits implemented for [`SetReducerFlags`].
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    pub set_reducer_flags: SetReducerFlags,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::Event<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for EventContext {
    type Event = __sdk::Event<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            set_reducer_flags: SetReducerFlags { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for EventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for EventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type SetReducerFlags = SetReducerFlags;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }
    fn set_reducer_flags(&self) -> &Self::SetReducerFlags {
        &self.set_reducer_flags
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::EventContext for EventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::ReducerEvent`],
/// passed to on-reducer callbacks.
pub struct ReducerEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to setting the call-flags of each reducer defined for each reducer defined by the module
    /// via extension traits implemented for [`SetReducerFlags`].
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    pub set_reducer_flags: SetReducerFlags,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::ReducerEvent<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ReducerEventContext {
    type Event = __sdk::ReducerEvent<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            set_reducer_flags: SetReducerFlags { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ReducerEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ReducerEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type SetReducerFlags = SetReducerFlags;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }
    fn set_reducer_flags(&self) -> &Self::SetReducerFlags {
        &self.set_reducer_flags
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ReducerEventContext for ReducerEventContext {}

/// An [`__sdk::DbContext`] passed to procedure callbacks.
pub struct ProcedureEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to setting the call-flags of each reducer defined for each reducer defined by the module
    /// via extension traits implemented for [`SetReducerFlags`].
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    pub set_reducer_flags: SetReducerFlags,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ProcedureEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            set_reducer_flags: SetReducerFlags { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for ProcedureEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ProcedureEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type SetReducerFlags = SetReducerFlags;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }
    fn set_reducer_flags(&self) -> &Self::SetReducerFlags {
        &self.set_reducer_flags
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ProcedureEventContext for ProcedureEventContext {}

/// An [`__sdk::DbContext`] passed to [`__sdk::SubscriptionBuilder::on_applied`] and [`SubscriptionHandle::unsubscribe_then`] callbacks.
pub struct SubscriptionEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to setting the call-flags of each reducer defined for each reducer defined by the module
    /// via extension traits implemented for [`SetReducerFlags`].
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    pub set_reducer_flags: SetReducerFlags,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for SubscriptionEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            set_reducer_flags: SetReducerFlags { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for SubscriptionEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for SubscriptionEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type SetReducerFlags = SetReducerFlags;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }
    fn set_reducer_flags(&self) -> &Self::SetReducerFlags {
        &self.set_reducer_flags
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::SubscriptionEventContext for SubscriptionEventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Error`],
/// passed to [`__sdk::DbConnectionBuilder::on_disconnect`], [`__sdk::DbConnectionBuilder::on_connect_error`] and [`__sdk::SubscriptionBuilder::on_error`] callbacks.
pub struct ErrorContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to setting the call-flags of each reducer defined for each reducer defined by the module
    /// via extension traits implemented for [`SetReducerFlags`].
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    pub set_reducer_flags: SetReducerFlags,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: Option<__sdk::Error>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ErrorContext {
    type Event = Option<__sdk::Error>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            set_reducer_flags: SetReducerFlags { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ErrorContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ErrorContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type SetReducerFlags = SetReducerFlags;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }
    fn set_reducer_flags(&self) -> &Self::SetReducerFlags {
        &self.set_reducer_flags
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ErrorContext for ErrorContext {}

impl __sdk::SpacetimeModule for RemoteModule {
    type DbConnection = DbConnection;
    type EventContext = EventContext;
    type ReducerEventContext = ReducerEventContext;
    type ProcedureEventContext = ProcedureEventContext;
    type SubscriptionEventContext = SubscriptionEventContext;
    type ErrorContext = ErrorContext;
    type Reducer = Reducer;
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type SetReducerFlags = SetReducerFlags;
    type DbUpdate = DbUpdate;
    type AppliedDiff<'r> = AppliedDiff<'r>;
    type SubscriptionHandle = SubscriptionHandle;

    fn register_tables(client_cache: &mut __sdk::ClientCache<Self>) {
        chat_table::register_table(client_cache);
        client_table::register_table(client_cache);
        human_table::register_table(client_cache);
        message_table::register_table(client_cache);
        notification_table::register_table(client_cache);
        phone_auth_table::register_table(client_cache);
        qr_auth_table::register_table(client_cache);
        robot_table::register_table(client_cache);
    }
}
