// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::note_media_type::NoteMedia;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `note_media`.
///
/// Obtain a handle from the [`NoteMediaTableAccess::note_media`] method on [`super::RemoteTables`],
/// like `ctx.db.note_media()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.note_media().on_insert(...)`.
pub struct NoteMediaTableHandle<'ctx> {
    imp: __sdk::TableHandle<NoteMedia>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `note_media`.
///
/// Implemented for [`super::RemoteTables`].
pub trait NoteMediaTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`NoteMediaTableHandle`], which mediates access to the table `note_media`.
    fn note_media(&self) -> NoteMediaTableHandle<'_>;
}

impl NoteMediaTableAccess for super::RemoteTables {
    fn note_media(&self) -> NoteMediaTableHandle<'_> {
        NoteMediaTableHandle {
            imp: self.imp.get_table::<NoteMedia>("note_media"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct NoteMediaInsertCallbackId(__sdk::CallbackId);
pub struct NoteMediaDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for NoteMediaTableHandle<'ctx> {
    type Row = NoteMedia;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = NoteMedia> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = NoteMediaInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NoteMediaInsertCallbackId {
        NoteMediaInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: NoteMediaInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = NoteMediaDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NoteMediaDeleteCallbackId {
        NoteMediaDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: NoteMediaDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<NoteMedia>("note_media");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct NoteMediaUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for NoteMediaTableHandle<'ctx> {
    type UpdateCallbackId = NoteMediaUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> NoteMediaUpdateCallbackId {
        NoteMediaUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: NoteMediaUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<NoteMedia>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<NoteMedia>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `note_media`,
/// which allows point queries on the field of the same name
/// via the [`NoteMediaIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.note_media().id().find(...)`.
pub struct NoteMediaIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<NoteMedia, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> NoteMediaTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `note_media`.
    pub fn id(&self) -> NoteMediaIdUnique<'ctx> {
        NoteMediaIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> NoteMediaIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<NoteMedia> {
        self.imp.find(col_val)
    }
}
