// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::note_qa_type::NoteQa;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `note_qa`.
///
/// Obtain a handle from the [`NoteQaTableAccess::note_qa`] method on [`super::RemoteTables`],
/// like `ctx.db.note_qa()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.note_qa().on_insert(...)`.
pub struct NoteQaTableHandle<'ctx> {
    imp: __sdk::TableHandle<NoteQa>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `note_qa`.
///
/// Implemented for [`super::RemoteTables`].
pub trait NoteQaTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`NoteQaTableHandle`], which mediates access to the table `note_qa`.
    fn note_qa(&self) -> NoteQaTableHandle<'_>;
}

impl NoteQaTableAccess for super::RemoteTables {
    fn note_qa(&self) -> NoteQaTableHandle<'_> {
        NoteQaTableHandle {
            imp: self.imp.get_table::<NoteQa>("note_qa"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct NoteQaInsertCallbackId(__sdk::CallbackId);
pub struct NoteQaDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for NoteQaTableHandle<'ctx> {
    type Row = NoteQa;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = NoteQa> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = NoteQaInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NoteQaInsertCallbackId {
        NoteQaInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: NoteQaInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = NoteQaDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NoteQaDeleteCallbackId {
        NoteQaDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: NoteQaDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<NoteQa>("note_qa");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct NoteQaUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for NoteQaTableHandle<'ctx> {
    type UpdateCallbackId = NoteQaUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> NoteQaUpdateCallbackId {
        NoteQaUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: NoteQaUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<NoteQa>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<NoteQa>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `note_qa`,
/// which allows point queries on the field of the same name
/// via the [`NoteQaIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.note_qa().id().find(...)`.
pub struct NoteQaIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<NoteQa, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> NoteQaTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `note_qa`.
    pub fn id(&self) -> NoteQaIdUnique<'ctx> {
        NoteQaIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> NoteQaIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<NoteQa> {
        self.imp.find(col_val)
    }
}
