// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::phone_auth_step_type::PhoneAuthStep;
use super::phone_auth_type::PhoneAuth;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `phone_auth`.
///
/// Obtain a handle from the [`PhoneAuthTableAccess::phone_auth`] method on [`super::RemoteTables`],
/// like `ctx.db.phone_auth()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.phone_auth().on_insert(...)`.
pub struct PhoneAuthTableHandle<'ctx> {
    imp: __sdk::TableHandle<PhoneAuth>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `phone_auth`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PhoneAuthTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PhoneAuthTableHandle`], which mediates access to the table `phone_auth`.
    fn phone_auth(&self) -> PhoneAuthTableHandle<'_>;
}

impl PhoneAuthTableAccess for super::RemoteTables {
    fn phone_auth(&self) -> PhoneAuthTableHandle<'_> {
        PhoneAuthTableHandle {
            imp: self.imp.get_table::<PhoneAuth>("phone_auth"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PhoneAuthInsertCallbackId(__sdk::CallbackId);
pub struct PhoneAuthDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PhoneAuthTableHandle<'ctx> {
    type Row = PhoneAuth;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PhoneAuth> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PhoneAuthInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PhoneAuthInsertCallbackId {
        PhoneAuthInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PhoneAuthInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PhoneAuthDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PhoneAuthDeleteCallbackId {
        PhoneAuthDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PhoneAuthDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PhoneAuth>("phone_auth");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct PhoneAuthUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PhoneAuthTableHandle<'ctx> {
    type UpdateCallbackId = PhoneAuthUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PhoneAuthUpdateCallbackId {
        PhoneAuthUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PhoneAuthUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<PhoneAuth>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PhoneAuth>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `phone_auth`,
/// which allows point queries on the field of the same name
/// via the [`PhoneAuthIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.phone_auth().id().find(...)`.
pub struct PhoneAuthIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PhoneAuth, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PhoneAuthTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `phone_auth`.
    pub fn id(&self) -> PhoneAuthIdUnique<'ctx> {
        PhoneAuthIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PhoneAuthIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<PhoneAuth> {
        self.imp.find(col_val)
    }
}
