// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::phone_auth_step_type::PhoneAuthStep;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PhoneAuth {
    pub id: u64,
    pub owner_user_id: __sdk::Identity,
    pub client_id: u64,
    pub phone: String,
    pub step: PhoneAuthStep,
    pub phone_code_hash: Option<String>,
    pub login_code: Option<String>,
    pub password_token: Option<String>,
    pub password: Option<String>,
    pub password_hint: Option<String>,
    pub error: Option<String>,
    pub assigned_robot: Option<__sdk::Identity>,
    pub created_at: __sdk::Timestamp,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for PhoneAuth {
    type Module = super::RemoteModule;
}
