// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::password_token_type::PasswordToken;
use super::qr_token_type::QrToken;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub enum PollQrLoginOutput {
    Pending,

    Token(QrToken),

    Success,

    PasswordRequired(PasswordToken),

    Failed(String),
}

impl __sdk::InModule for PollQrLoginOutput {
    type Module = super::RemoteModule;
}
