// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::qa_type::Qa;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `qa`.
///
/// Obtain a handle from the [`QaTableAccess::qa`] method on [`super::RemoteTables`],
/// like `ctx.db.qa()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.qa().on_insert(...)`.
pub struct QaTableHandle<'ctx> {
    imp: __sdk::TableHandle<Qa>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `qa`.
///
/// Implemented for [`super::RemoteTables`].
pub trait QaTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`QaTableHandle`], which mediates access to the table `qa`.
    fn qa(&self) -> QaTableHandle<'_>;
}

impl QaTableAccess for super::RemoteTables {
    fn qa(&self) -> QaTableHandle<'_> {
        QaTableHandle {
            imp: self.imp.get_table::<Qa>("qa"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct QaInsertCallbackId(__sdk::CallbackId);
pub struct QaDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for QaTableHandle<'ctx> {
    type Row = Qa;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Qa> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = QaInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> QaInsertCallbackId {
        QaInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: QaInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = QaDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> QaDeleteCallbackId {
        QaDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: QaDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Qa>("qa");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct QaUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for QaTableHandle<'ctx> {
    type UpdateCallbackId = QaUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> QaUpdateCallbackId {
        QaUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: QaUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Qa>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Qa>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `qa`,
/// which allows point queries on the field of the same name
/// via the [`QaIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.qa().id().find(...)`.
pub struct QaIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Qa, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> QaTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `qa`.
    pub fn id(&self) -> QaIdUnique<'ctx> {
        QaIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> QaIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Qa> {
        self.imp.find(col_val)
    }
}
