// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::qr_auth_step_type::QrAuthStep;
use super::qr_auth_type::QrAuth;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `qr_auth`.
///
/// Obtain a handle from the [`QrAuthTableAccess::qr_auth`] method on [`super::RemoteTables`],
/// like `ctx.db.qr_auth()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.qr_auth().on_insert(...)`.
pub struct QrAuthTableHandle<'ctx> {
    imp: __sdk::TableHandle<QrAuth>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `qr_auth`.
///
/// Implemented for [`super::RemoteTables`].
pub trait QrAuthTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`QrAuthTableHandle`], which mediates access to the table `qr_auth`.
    fn qr_auth(&self) -> QrAuthTableHandle<'_>;
}

impl QrAuthTableAccess for super::RemoteTables {
    fn qr_auth(&self) -> QrAuthTableHandle<'_> {
        QrAuthTableHandle {
            imp: self.imp.get_table::<QrAuth>("qr_auth"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct QrAuthInsertCallbackId(__sdk::CallbackId);
pub struct QrAuthDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for QrAuthTableHandle<'ctx> {
    type Row = QrAuth;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = QrAuth> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = QrAuthInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> QrAuthInsertCallbackId {
        QrAuthInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: QrAuthInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = QrAuthDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> QrAuthDeleteCallbackId {
        QrAuthDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: QrAuthDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<QrAuth>("qr_auth");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct QrAuthUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for QrAuthTableHandle<'ctx> {
    type UpdateCallbackId = QrAuthUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> QrAuthUpdateCallbackId {
        QrAuthUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: QrAuthUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<QrAuth>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<QrAuth>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `qr_auth`,
/// which allows point queries on the field of the same name
/// via the [`QrAuthIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.qr_auth().id().find(...)`.
pub struct QrAuthIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<QrAuth, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> QrAuthTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `qr_auth`.
    pub fn id(&self) -> QrAuthIdUnique<'ctx> {
        QrAuthIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> QrAuthIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<QrAuth> {
        self.imp.find(col_val)
    }
}
