// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::qr_auth_step_type::QrAuthStep;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct QrAuth {
    pub id: u64,
    pub owner_user_id: __sdk::Identity,
    pub step: QrAuthStep,
    pub qr_url: Option<String>,
    pub qr_expires: Option<i32>,
    pub telegram_user_id: Option<i64>,
    pub error: Option<String>,
    pub assigned_robot: Option<__sdk::Identity>,
    pub created_at: __sdk::Timestamp,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for QrAuth {
    type Module = super::RemoteModule;
}
