// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::request_login_code_output_type::RequestLoginCodeOutput;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct RequestLoginCode {
    pub phone: String,
    pub output: RequestLoginCodeOutput,
}

impl __sdk::InModule for RequestLoginCode {
    type Module = super::RemoteModule;
}
