// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RobotClaimQrAuthArgs {
    pub auth_id: u64,
}

impl From<RobotClaimQrAuthArgs> for super::Reducer {
    fn from(args: RobotClaimQrAuthArgs) -> Self {
        Self::RobotClaimQrAuth {
            auth_id: args.auth_id,
        }
    }
}

impl __sdk::InModule for RobotClaimQrAuthArgs {
    type Module = super::RemoteModule;
}

pub struct RobotClaimQrAuthCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `robot_claim_qr_auth`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait robot_claim_qr_auth {
    /// Request that the remote module invoke the reducer `robot_claim_qr_auth` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_robot_claim_qr_auth`] callbacks.
    fn robot_claim_qr_auth(&self, auth_id: u64) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `robot_claim_qr_auth`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`RobotClaimQrAuthCallbackId`] can be passed to [`Self::remove_on_robot_claim_qr_auth`]
    /// to cancel the callback.
    fn on_robot_claim_qr_auth(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64) + Send + 'static,
    ) -> RobotClaimQrAuthCallbackId;
    /// Cancel a callback previously registered by [`Self::on_robot_claim_qr_auth`],
    /// causing it not to run in the future.
    fn remove_on_robot_claim_qr_auth(&self, callback: RobotClaimQrAuthCallbackId);
}

impl robot_claim_qr_auth for super::RemoteReducers {
    fn robot_claim_qr_auth(&self, auth_id: u64) -> __sdk::Result<()> {
        self.imp
            .call_reducer("robot_claim_qr_auth", RobotClaimQrAuthArgs { auth_id })
    }
    fn on_robot_claim_qr_auth(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64) + Send + 'static,
    ) -> RobotClaimQrAuthCallbackId {
        RobotClaimQrAuthCallbackId(self.imp.on_reducer(
            "robot_claim_qr_auth",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::RobotClaimQrAuth { auth_id },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, auth_id)
            }),
        ))
    }
    fn remove_on_robot_claim_qr_auth(&self, callback: RobotClaimQrAuthCallbackId) {
        self.imp
            .remove_on_reducer("robot_claim_qr_auth", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `robot_claim_qr_auth`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_robot_claim_qr_auth {
    /// Set the call-reducer flags for the reducer `robot_claim_qr_auth` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn robot_claim_qr_auth(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_robot_claim_qr_auth for super::SetReducerFlags {
    fn robot_claim_qr_auth(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("robot_claim_qr_auth", flags);
    }
}
