// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::verify_code_result_type::VerifyCodeResult;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RobotCompleteVerifyCodeArgs {
    pub auth_id: u64,
    pub result: VerifyCodeResult,
}

impl From<RobotCompleteVerifyCodeArgs> for super::Reducer {
    fn from(args: RobotCompleteVerifyCodeArgs) -> Self {
        Self::RobotCompleteVerifyCode {
            auth_id: args.auth_id,
            result: args.result,
        }
    }
}

impl __sdk::InModule for RobotCompleteVerifyCodeArgs {
    type Module = super::RemoteModule;
}

pub struct RobotCompleteVerifyCodeCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `robot_complete_verify_code`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait robot_complete_verify_code {
    /// Request that the remote module invoke the reducer `robot_complete_verify_code` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_robot_complete_verify_code`] callbacks.
    fn robot_complete_verify_code(
        &self,
        auth_id: u64,
        result: VerifyCodeResult,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `robot_complete_verify_code`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`RobotCompleteVerifyCodeCallbackId`] can be passed to [`Self::remove_on_robot_complete_verify_code`]
    /// to cancel the callback.
    fn on_robot_complete_verify_code(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64, &VerifyCodeResult) + Send + 'static,
    ) -> RobotCompleteVerifyCodeCallbackId;
    /// Cancel a callback previously registered by [`Self::on_robot_complete_verify_code`],
    /// causing it not to run in the future.
    fn remove_on_robot_complete_verify_code(&self, callback: RobotCompleteVerifyCodeCallbackId);
}

impl robot_complete_verify_code for super::RemoteReducers {
    fn robot_complete_verify_code(
        &self,
        auth_id: u64,
        result: VerifyCodeResult,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "robot_complete_verify_code",
            RobotCompleteVerifyCodeArgs { auth_id, result },
        )
    }
    fn on_robot_complete_verify_code(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64, &VerifyCodeResult) + Send + 'static,
    ) -> RobotCompleteVerifyCodeCallbackId {
        RobotCompleteVerifyCodeCallbackId(self.imp.on_reducer(
            "robot_complete_verify_code",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::RobotCompleteVerifyCode { auth_id, result },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, auth_id, result)
            }),
        ))
    }
    fn remove_on_robot_complete_verify_code(&self, callback: RobotCompleteVerifyCodeCallbackId) {
        self.imp
            .remove_on_reducer("robot_complete_verify_code", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `robot_complete_verify_code`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_robot_complete_verify_code {
    /// Set the call-reducer flags for the reducer `robot_complete_verify_code` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn robot_complete_verify_code(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_robot_complete_verify_code for super::SetReducerFlags {
    fn robot_complete_verify_code(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("robot_complete_verify_code", flags);
    }
}
