// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::verify_password_result_type::VerifyPasswordResult;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RobotCompleteVerifyPasswordArgs {
    pub auth_id: u64,
    pub result: VerifyPasswordResult,
}

impl From<RobotCompleteVerifyPasswordArgs> for super::Reducer {
    fn from(args: RobotCompleteVerifyPasswordArgs) -> Self {
        Self::RobotCompleteVerifyPassword {
            auth_id: args.auth_id,
            result: args.result,
        }
    }
}

impl __sdk::InModule for RobotCompleteVerifyPasswordArgs {
    type Module = super::RemoteModule;
}

pub struct RobotCompleteVerifyPasswordCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `robot_complete_verify_password`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait robot_complete_verify_password {
    /// Request that the remote module invoke the reducer `robot_complete_verify_password` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_robot_complete_verify_password`] callbacks.
    fn robot_complete_verify_password(
        &self,
        auth_id: u64,
        result: VerifyPasswordResult,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `robot_complete_verify_password`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`RobotCompleteVerifyPasswordCallbackId`] can be passed to [`Self::remove_on_robot_complete_verify_password`]
    /// to cancel the callback.
    fn on_robot_complete_verify_password(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64, &VerifyPasswordResult) + Send + 'static,
    ) -> RobotCompleteVerifyPasswordCallbackId;
    /// Cancel a callback previously registered by [`Self::on_robot_complete_verify_password`],
    /// causing it not to run in the future.
    fn remove_on_robot_complete_verify_password(
        &self,
        callback: RobotCompleteVerifyPasswordCallbackId,
    );
}

impl robot_complete_verify_password for super::RemoteReducers {
    fn robot_complete_verify_password(
        &self,
        auth_id: u64,
        result: VerifyPasswordResult,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "robot_complete_verify_password",
            RobotCompleteVerifyPasswordArgs { auth_id, result },
        )
    }
    fn on_robot_complete_verify_password(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64, &VerifyPasswordResult)
        + Send
        + 'static,
    ) -> RobotCompleteVerifyPasswordCallbackId {
        RobotCompleteVerifyPasswordCallbackId(
            self.imp.on_reducer(
                "robot_complete_verify_password",
                Box::new(move |ctx: &super::ReducerEventContext| {
                    let super::ReducerEventContext {
                        event:
                            __sdk::ReducerEvent {
                                reducer:
                                    super::Reducer::RobotCompleteVerifyPassword { auth_id, result },
                                ..
                            },
                        ..
                    } = ctx
                    else {
                        unreachable!()
                    };
                    callback(ctx, auth_id, result)
                }),
            ),
        )
    }
    fn remove_on_robot_complete_verify_password(
        &self,
        callback: RobotCompleteVerifyPasswordCallbackId,
    ) {
        self.imp
            .remove_on_reducer("robot_complete_verify_password", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `robot_complete_verify_password`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_robot_complete_verify_password {
    /// Set the call-reducer flags for the reducer `robot_complete_verify_password` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn robot_complete_verify_password(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_robot_complete_verify_password for super::SetReducerFlags {
    fn robot_complete_verify_password(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("robot_complete_verify_password", flags);
    }
}
