// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RobotUpdateQrTokenArgs {
    pub auth_id: u64,
    pub url: String,
    pub expires: i32,
}

impl From<RobotUpdateQrTokenArgs> for super::Reducer {
    fn from(args: RobotUpdateQrTokenArgs) -> Self {
        Self::RobotUpdateQrToken {
            auth_id: args.auth_id,
            url: args.url,
            expires: args.expires,
        }
    }
}

impl __sdk::InModule for RobotUpdateQrTokenArgs {
    type Module = super::RemoteModule;
}

pub struct RobotUpdateQrTokenCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `robot_update_qr_token`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait robot_update_qr_token {
    /// Request that the remote module invoke the reducer `robot_update_qr_token` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_robot_update_qr_token`] callbacks.
    fn robot_update_qr_token(&self, auth_id: u64, url: String, expires: i32) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `robot_update_qr_token`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`RobotUpdateQrTokenCallbackId`] can be passed to [`Self::remove_on_robot_update_qr_token`]
    /// to cancel the callback.
    fn on_robot_update_qr_token(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64, &String, &i32) + Send + 'static,
    ) -> RobotUpdateQrTokenCallbackId;
    /// Cancel a callback previously registered by [`Self::on_robot_update_qr_token`],
    /// causing it not to run in the future.
    fn remove_on_robot_update_qr_token(&self, callback: RobotUpdateQrTokenCallbackId);
}

impl robot_update_qr_token for super::RemoteReducers {
    fn robot_update_qr_token(&self, auth_id: u64, url: String, expires: i32) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "robot_update_qr_token",
            RobotUpdateQrTokenArgs {
                auth_id,
                url,
                expires,
            },
        )
    }
    fn on_robot_update_qr_token(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64, &String, &i32) + Send + 'static,
    ) -> RobotUpdateQrTokenCallbackId {
        RobotUpdateQrTokenCallbackId(self.imp.on_reducer(
            "robot_update_qr_token",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::RobotUpdateQrToken {
                                    auth_id,
                                    url,
                                    expires,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, auth_id, url, expires)
            }),
        ))
    }
    fn remove_on_robot_update_qr_token(&self, callback: RobotUpdateQrTokenCallbackId) {
        self.imp
            .remove_on_reducer("robot_update_qr_token", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `robot_update_qr_token`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_robot_update_qr_token {
    /// Set the call-reducer flags for the reducer `robot_update_qr_token` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn robot_update_qr_token(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_robot_update_qr_token for super::SetReducerFlags {
    fn robot_update_qr_token(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("robot_update_qr_token", flags);
    }
}
