// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct StartPhoneAuthArgs {
    pub phone: String,
}

impl From<StartPhoneAuthArgs> for super::Reducer {
    fn from(args: StartPhoneAuthArgs) -> Self {
        Self::StartPhoneAuth { phone: args.phone }
    }
}

impl __sdk::InModule for StartPhoneAuthArgs {
    type Module = super::RemoteModule;
}

pub struct StartPhoneAuthCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `start_phone_auth`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait start_phone_auth {
    /// Request that the remote module invoke the reducer `start_phone_auth` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_start_phone_auth`] callbacks.
    fn start_phone_auth(&self, phone: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `start_phone_auth`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`StartPhoneAuthCallbackId`] can be passed to [`Self::remove_on_start_phone_auth`]
    /// to cancel the callback.
    fn on_start_phone_auth(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> StartPhoneAuthCallbackId;
    /// Cancel a callback previously registered by [`Self::on_start_phone_auth`],
    /// causing it not to run in the future.
    fn remove_on_start_phone_auth(&self, callback: StartPhoneAuthCallbackId);
}

impl start_phone_auth for super::RemoteReducers {
    fn start_phone_auth(&self, phone: String) -> __sdk::Result<()> {
        self.imp
            .call_reducer("start_phone_auth", StartPhoneAuthArgs { phone })
    }
    fn on_start_phone_auth(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> StartPhoneAuthCallbackId {
        StartPhoneAuthCallbackId(self.imp.on_reducer(
            "start_phone_auth",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::StartPhoneAuth { phone },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, phone)
            }),
        ))
    }
    fn remove_on_start_phone_auth(&self, callback: StartPhoneAuthCallbackId) {
        self.imp.remove_on_reducer("start_phone_auth", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `start_phone_auth`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_start_phone_auth {
    /// Set the call-reducer flags for the reducer `start_phone_auth` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn start_phone_auth(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_start_phone_auth for super::SetReducerFlags {
    fn start_phone_auth(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("start_phone_auth", flags);
    }
}
