// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SubmitPasswordArgs {
    pub auth_id: u64,
    pub password: String,
}

impl From<SubmitPasswordArgs> for super::Reducer {
    fn from(args: SubmitPasswordArgs) -> Self {
        Self::SubmitPassword {
            auth_id: args.auth_id,
            password: args.password,
        }
    }
}

impl __sdk::InModule for SubmitPasswordArgs {
    type Module = super::RemoteModule;
}

pub struct SubmitPasswordCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `submit_password`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait submit_password {
    /// Request that the remote module invoke the reducer `submit_password` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_submit_password`] callbacks.
    fn submit_password(&self, auth_id: u64, password: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `submit_password`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`SubmitPasswordCallbackId`] can be passed to [`Self::remove_on_submit_password`]
    /// to cancel the callback.
    fn on_submit_password(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64, &String) + Send + 'static,
    ) -> SubmitPasswordCallbackId;
    /// Cancel a callback previously registered by [`Self::on_submit_password`],
    /// causing it not to run in the future.
    fn remove_on_submit_password(&self, callback: SubmitPasswordCallbackId);
}

impl submit_password for super::RemoteReducers {
    fn submit_password(&self, auth_id: u64, password: String) -> __sdk::Result<()> {
        self.imp
            .call_reducer("submit_password", SubmitPasswordArgs { auth_id, password })
    }
    fn on_submit_password(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64, &String) + Send + 'static,
    ) -> SubmitPasswordCallbackId {
        SubmitPasswordCallbackId(self.imp.on_reducer(
            "submit_password",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::SubmitPassword { auth_id, password },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, auth_id, password)
            }),
        ))
    }
    fn remove_on_submit_password(&self, callback: SubmitPasswordCallbackId) {
        self.imp.remove_on_reducer("submit_password", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `submit_password`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_submit_password {
    /// Set the call-reducer flags for the reducer `submit_password` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn submit_password(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_submit_password for super::SetReducerFlags {
    fn submit_password(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("submit_password", flags);
    }
}
