// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SubmitLoginCodeArgs {
    pub auth_id: u64,
    pub code: String,
}

impl From<SubmitLoginCodeArgs> for super::Reducer {
    fn from(args: SubmitLoginCodeArgs) -> Self {
        Self::SubmitLoginCode {
            auth_id: args.auth_id,
            code: args.code,
        }
    }
}

impl __sdk::InModule for SubmitLoginCodeArgs {
    type Module = super::RemoteModule;
}

pub struct SubmitLoginCodeCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `submit_login_code`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait submit_login_code {
    /// Request that the remote module invoke the reducer `submit_login_code` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_submit_login_code`] callbacks.
    fn submit_login_code(&self, auth_id: u64, code: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `submit_login_code`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`SubmitLoginCodeCallbackId`] can be passed to [`Self::remove_on_submit_login_code`]
    /// to cancel the callback.
    fn on_submit_login_code(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64, &String) + Send + 'static,
    ) -> SubmitLoginCodeCallbackId;
    /// Cancel a callback previously registered by [`Self::on_submit_login_code`],
    /// causing it not to run in the future.
    fn remove_on_submit_login_code(&self, callback: SubmitLoginCodeCallbackId);
}

impl submit_login_code for super::RemoteReducers {
    fn submit_login_code(&self, auth_id: u64, code: String) -> __sdk::Result<()> {
        self.imp
            .call_reducer("submit_login_code", SubmitLoginCodeArgs { auth_id, code })
    }
    fn on_submit_login_code(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64, &String) + Send + 'static,
    ) -> SubmitLoginCodeCallbackId {
        SubmitLoginCodeCallbackId(self.imp.on_reducer(
            "submit_login_code",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::SubmitLoginCode { auth_id, code },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, auth_id, code)
            }),
        ))
    }
    fn remove_on_submit_login_code(&self, callback: SubmitLoginCodeCallbackId) {
        self.imp.remove_on_reducer("submit_login_code", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `submit_login_code`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_submit_login_code {
    /// Set the call-reducer flags for the reducer `submit_login_code` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn submit_login_code(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_submit_login_code for super::SetReducerFlags {
    fn submit_login_code(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("submit_login_code", flags);
    }
}
