// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::task_payload_type::TaskPayload;
use super::task_status_type::TaskStatus;
use super::task_type::Task;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `task`.
///
/// Obtain a handle from the [`TaskTableAccess::task`] method on [`super::RemoteTables`],
/// like `ctx.db.task()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.task().on_insert(...)`.
pub struct TaskTableHandle<'ctx> {
    imp: __sdk::TableHandle<Task>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `task`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TaskTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TaskTableHandle`], which mediates access to the table `task`.
    fn task(&self) -> TaskTableHandle<'_>;
}

impl TaskTableAccess for super::RemoteTables {
    fn task(&self) -> TaskTableHandle<'_> {
        TaskTableHandle {
            imp: self.imp.get_table::<Task>("task"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TaskInsertCallbackId(__sdk::CallbackId);
pub struct TaskDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TaskTableHandle<'ctx> {
    type Row = Task;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Task> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TaskInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TaskInsertCallbackId {
        TaskInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TaskInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TaskDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TaskDeleteCallbackId {
        TaskDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TaskDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Task>("task");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct TaskUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TaskTableHandle<'ctx> {
    type UpdateCallbackId = TaskUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TaskUpdateCallbackId {
        TaskUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TaskUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Task>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Task>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `task`,
/// which allows point queries on the field of the same name
/// via the [`TaskIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.task().id().find(...)`.
pub struct TaskIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Task, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TaskTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `task`.
    pub fn id(&self) -> TaskIdUnique<'ctx> {
        TaskIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TaskIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Task> {
        self.imp.find(col_val)
    }
}
