// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::display_message_type::DisplayMessage;
use super::generate_qr_code_type::GenerateQrCode;
use super::receive_login_code_type::ReceiveLoginCode;
use super::receive_password_type::ReceivePassword;
use super::send_login_code_type::SendLoginCode;
use super::verify_login_code_type::VerifyLoginCode;
use super::verify_password_type::VerifyPassword;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub enum TaskPayload {
    SendLoginCode(SendLoginCode),

    ReceiveLoginCode(ReceiveLoginCode),

    VerifyLoginCode(VerifyLoginCode),

    ReceivePassword(ReceivePassword),

    VerifyPassword(VerifyPassword),

    GenerateQrCode(GenerateQrCode),

    DisplayMessage(DisplayMessage),
}

impl __sdk::InModule for TaskPayload {
    type Module = super::RemoteModule;
}
