// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::task_payload_type::TaskPayload;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateTaskArgs {
    pub task_id: String,
    pub payload: TaskPayload,
}

impl From<UpdateTaskArgs> for super::Reducer {
    fn from(args: UpdateTaskArgs) -> Self {
        Self::UpdateTask {
            task_id: args.task_id,
            payload: args.payload,
        }
    }
}

impl __sdk::InModule for UpdateTaskArgs {
    type Module = super::RemoteModule;
}

pub struct UpdateTaskCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_task`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_task {
    /// Request that the remote module invoke the reducer `update_task` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_update_task`] callbacks.
    fn update_task(&self, task_id: String, payload: TaskPayload) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `update_task`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`UpdateTaskCallbackId`] can be passed to [`Self::remove_on_update_task`]
    /// to cancel the callback.
    fn on_update_task(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String, &TaskPayload) + Send + 'static,
    ) -> UpdateTaskCallbackId;
    /// Cancel a callback previously registered by [`Self::on_update_task`],
    /// causing it not to run in the future.
    fn remove_on_update_task(&self, callback: UpdateTaskCallbackId);
}

impl update_task for super::RemoteReducers {
    fn update_task(&self, task_id: String, payload: TaskPayload) -> __sdk::Result<()> {
        self.imp
            .call_reducer("update_task", UpdateTaskArgs { task_id, payload })
    }
    fn on_update_task(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String, &TaskPayload) + Send + 'static,
    ) -> UpdateTaskCallbackId {
        UpdateTaskCallbackId(self.imp.on_reducer(
            "update_task",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::UpdateTask { task_id, payload },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, task_id, payload)
            }),
        ))
    }
    fn remove_on_update_task(&self, callback: UpdateTaskCallbackId) {
        self.imp.remove_on_reducer("update_task", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `update_task`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_update_task {
    /// Set the call-reducer flags for the reducer `update_task` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn update_task(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_update_task for super::SetReducerFlags {
    fn update_task(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("update_task", flags);
    }
}
