// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::chat_type::Chat;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpsertChatArgs {
    pub chat: Chat,
}

impl From<UpsertChatArgs> for super::Reducer {
    fn from(args: UpsertChatArgs) -> Self {
        Self::UpsertChat { chat: args.chat }
    }
}

impl __sdk::InModule for UpsertChatArgs {
    type Module = super::RemoteModule;
}

pub struct UpsertChatCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `upsert_chat`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait upsert_chat {
    /// Request that the remote module invoke the reducer `upsert_chat` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_upsert_chat`] callbacks.
    fn upsert_chat(&self, chat: Chat) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `upsert_chat`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`UpsertChatCallbackId`] can be passed to [`Self::remove_on_upsert_chat`]
    /// to cancel the callback.
    fn on_upsert_chat(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &Chat) + Send + 'static,
    ) -> UpsertChatCallbackId;
    /// Cancel a callback previously registered by [`Self::on_upsert_chat`],
    /// causing it not to run in the future.
    fn remove_on_upsert_chat(&self, callback: UpsertChatCallbackId);
}

impl upsert_chat for super::RemoteReducers {
    fn upsert_chat(&self, chat: Chat) -> __sdk::Result<()> {
        self.imp
            .call_reducer("upsert_chat", UpsertChatArgs { chat })
    }
    fn on_upsert_chat(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &Chat) + Send + 'static,
    ) -> UpsertChatCallbackId {
        UpsertChatCallbackId(self.imp.on_reducer(
            "upsert_chat",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::UpsertChat { chat },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, chat)
            }),
        ))
    }
    fn remove_on_upsert_chat(&self, callback: UpsertChatCallbackId) {
        self.imp.remove_on_reducer("upsert_chat", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `upsert_chat`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_upsert_chat {
    /// Set the call-reducer flags for the reducer `upsert_chat` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn upsert_chat(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_upsert_chat for super::SetReducerFlags {
    fn upsert_chat(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("upsert_chat", flags);
    }
}
