// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::message_type::Message;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpsertMessageArgs {
    pub message: Message,
}

impl From<UpsertMessageArgs> for super::Reducer {
    fn from(args: UpsertMessageArgs) -> Self {
        Self::UpsertMessage {
            message: args.message,
        }
    }
}

impl __sdk::InModule for UpsertMessageArgs {
    type Module = super::RemoteModule;
}

pub struct UpsertMessageCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `upsert_message`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait upsert_message {
    /// Request that the remote module invoke the reducer `upsert_message` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_upsert_message`] callbacks.
    fn upsert_message(&self, message: Message) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `upsert_message`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`UpsertMessageCallbackId`] can be passed to [`Self::remove_on_upsert_message`]
    /// to cancel the callback.
    fn on_upsert_message(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &Message) + Send + 'static,
    ) -> UpsertMessageCallbackId;
    /// Cancel a callback previously registered by [`Self::on_upsert_message`],
    /// causing it not to run in the future.
    fn remove_on_upsert_message(&self, callback: UpsertMessageCallbackId);
}

impl upsert_message for super::RemoteReducers {
    fn upsert_message(&self, message: Message) -> __sdk::Result<()> {
        self.imp
            .call_reducer("upsert_message", UpsertMessageArgs { message })
    }
    fn on_upsert_message(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &Message) + Send + 'static,
    ) -> UpsertMessageCallbackId {
        UpsertMessageCallbackId(self.imp.on_reducer(
            "upsert_message",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::UpsertMessage { message },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, message)
            }),
        ))
    }
    fn remove_on_upsert_message(&self, callback: UpsertMessageCallbackId) {
        self.imp.remove_on_reducer("upsert_message", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `upsert_message`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_upsert_message {
    /// Set the call-reducer flags for the reducer `upsert_message` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn upsert_message(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_upsert_message for super::SetReducerFlags {
    fn upsert_message(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("upsert_message", flags);
    }
}
