// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::client_type::Client;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpsertClientArgs {
    pub client: Client,
}

impl From<UpsertClientArgs> for super::Reducer {
    fn from(args: UpsertClientArgs) -> Self {
        Self::UpsertClient {
            client: args.client,
        }
    }
}

impl __sdk::InModule for UpsertClientArgs {
    type Module = super::RemoteModule;
}

pub struct UpsertClientCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `upsert_client`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait upsert_client {
    /// Request that the remote module invoke the reducer `upsert_client` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_upsert_client`] callbacks.
    fn upsert_client(&self, client: Client) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `upsert_client`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`UpsertClientCallbackId`] can be passed to [`Self::remove_on_upsert_client`]
    /// to cancel the callback.
    fn on_upsert_client(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &Client) + Send + 'static,
    ) -> UpsertClientCallbackId;
    /// Cancel a callback previously registered by [`Self::on_upsert_client`],
    /// causing it not to run in the future.
    fn remove_on_upsert_client(&self, callback: UpsertClientCallbackId);
}

impl upsert_client for super::RemoteReducers {
    fn upsert_client(&self, client: Client) -> __sdk::Result<()> {
        self.imp
            .call_reducer("upsert_client", UpsertClientArgs { client })
    }
    fn on_upsert_client(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &Client) + Send + 'static,
    ) -> UpsertClientCallbackId {
        UpsertClientCallbackId(self.imp.on_reducer(
            "upsert_client",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::UpsertClient { client },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, client)
            }),
        ))
    }
    fn remove_on_upsert_client(&self, callback: UpsertClientCallbackId) {
        self.imp.remove_on_reducer("upsert_client", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `upsert_client`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_upsert_client {
    /// Set the call-reducer flags for the reducer `upsert_client` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn upsert_client(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_upsert_client for super::SetReducerFlags {
    fn upsert_client(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("upsert_client", flags);
    }
}
