//! Convex document types and conversion helpers.
//!
//! Type definitions are generated by convex-typegen in the `convex-backend` crate.
//! This module re-exports them with shorter aliases and adds Convex Value helpers.

use convex::{FunctionResult, Value};
use serde::Deserialize;

use crate::error::TaskError;

// Re-export generated types with shorter names
pub use convex_backend::ConvexApi;
pub use convex_backend::PhoneAuthsStep as PhoneAuthStep;
pub use convex_backend::PhoneAuthsTable as PhoneAuth;
pub use convex_backend::QrAuthsStep as QrAuthStep;
pub use convex_backend::QrAuthsTable as QrAuth;

// ============================================================================
// Value conversion
// ============================================================================

/// Convert a `convex::Value` to `serde_json::Value` for deserialization.
fn value_to_json(v: &Value) -> serde_json::Value {
    match v {
        Value::Null => serde_json::Value::Null,
        Value::Int64(n) => serde_json::json!(*n),
        Value::Float64(f) => serde_json::json!(*f),
        Value::Boolean(b) => serde_json::json!(*b),
        Value::String(s) => serde_json::Value::String(s.clone()),
        Value::Array(arr) => serde_json::Value::Array(arr.iter().map(value_to_json).collect()),
        Value::Object(obj) => {
            let map: serde_json::Map<String, serde_json::Value> =
                obj.iter().map(|(k, v)| (k.clone(), value_to_json(v))).collect();
            serde_json::Value::Object(map)
        }
        _ => serde_json::Value::Null,
    }
}

/// Parse a `FunctionResult` containing an array of documents.
fn parse_docs<T: for<'de> Deserialize<'de>>(result: &FunctionResult) -> Vec<T> {
    match result {
        FunctionResult::Value(Value::Array(items)) => items
            .iter()
            .filter_map(|item| {
                let json = value_to_json(item);
                serde_json::from_value(json).ok()
            })
            .collect(),
        _ => vec![],
    }
}

/// Parse phone auth documents from a subscription result.
pub fn parse_phone_auths(result: &FunctionResult) -> Vec<PhoneAuth> {
    parse_docs(result)
}

/// Parse QR auth documents from a subscription result.
pub fn parse_qr_auths(result: &FunctionResult) -> Vec<QrAuth> {
    parse_docs(result)
}

// ============================================================================
// Mutation helper
// ============================================================================

/// Unwrap a `FunctionResult` into `Ok(())` or a `TaskError`.
pub fn check_result(result: anyhow::Result<FunctionResult>) -> Result<(), TaskError> {
    match result {
        Ok(FunctionResult::Value(_)) => Ok(()),
        Ok(FunctionResult::ErrorMessage(msg)) => Err(TaskError::MutationFailed(msg)),
        Ok(FunctionResult::ConvexError(err)) => Err(TaskError::MutationFailed(err.message)),
        Err(e) => Err(TaskError::MutationFailed(e.to_string())),
    }
}
