//! Convex document types and conversion helpers.
//!
//! Type definitions are generated by convex-typegen in the `convex-backend` crate.
//! This module re-exports them with shorter aliases.

use convex_backend::MessagesUpsertMediaKind;
use messanger_interface::media::MediaKind;

use crate::error::TaskError;

// Re-export generated types with shorter names
pub use convex_backend::ClientsTable as Client;
pub use convex_backend::ConvexApi;
pub use convex_backend::PhoneAuthsStep as PhoneAuthStep;
pub use convex_backend::PhoneAuthsTable as PhoneAuth;
pub use convex_backend::QrAuthsStep as QrAuthStep;
pub use convex_backend::QrAuthsTable as QrAuth;

// ============================================================================
// Media kind conversions
// ============================================================================

/// Convert a `MediaKind` to the generated `MessagesUpsertMediaKind`.
pub fn to_upsert_media_kind(kind: MediaKind) -> MessagesUpsertMediaKind {
    match kind {
        MediaKind::Photo => MessagesUpsertMediaKind::Photo,
        MediaKind::Video => MessagesUpsertMediaKind::Video,
        MediaKind::VideoNote => MessagesUpsertMediaKind::VideoNote,
        MediaKind::Audio => MessagesUpsertMediaKind::Audio,
        MediaKind::Voice => MessagesUpsertMediaKind::Voice,
        MediaKind::Sticker => MessagesUpsertMediaKind::Sticker,
        MediaKind::Animation => MessagesUpsertMediaKind::Animation,
        MediaKind::Document => MessagesUpsertMediaKind::Document,
    }
}

// ============================================================================
// Mutation helper
// ============================================================================

/// Map `anyhow::Result<()>` from a typed mutation into `Result<(), TaskError>`.
pub fn check_result(result: anyhow::Result<()>) -> Result<(), TaskError> {
    result.map_err(|e| TaskError::MutationFailed(e.to_string()))
}
