[package]
name = "convex-backend"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "Generated Rust type bindings from Convex schema"

[dependencies]
anyhow = "1"
convex = "0.10.2"
futures-core = "0.3"
hack = { version = "0.1", path = "../../libs/hack" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
testcontainers = "0.27"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", features = ["json"] }
futures = "0.3"
# convex-typegen = { path = "../../../convex-typegen" }   
convex-typegen = { git = "https://github.com/nickcomua/convex-typegen.git" }
tempfile = "3"

[build-dependencies]
# convex-typegen = { path = "../../../convex-typegen" }
convex-typegen = { git = "https://github.com/nickcomua/convex-typegen.git" }