// biome-ignore-all lint: autogen
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/

export const commands = {
	async getChats(): Promise<Result<Chat[], string>> {
		try {
			return { status: "ok", data: await TAURI_INVOKE("get_chats") };
		} catch (e) {
			if (e instanceof Error) throw e;
			else return { status: "error", error: e as any };
		}
	},
	async getTopN(
		query: string,
		samples: number
	): Promise<Result<[number, string, WordDefinition][], string>> {
		try {
			return {
				status: "ok",
				data: await TAURI_INVOKE("get_top_n", { query, samples }),
			};
		} catch (e) {
			if (e instanceof Error) throw e;
			else return { status: "error", error: e as any };
		}
	},
	async updateChatPin(
		chatId: string,
		isPinned: boolean,
		pinedName: string | null
	): Promise<Result<null, string>> {
		try {
			return {
				status: "ok",
				data: await TAURI_INVOKE("update_chat_pin", {
					chatId,
					isPinned,
					pinedName,
				}),
			};
		} catch (e) {
			if (e instanceof Error) throw e;
			else return { status: "error", error: e as any };
		}
	},
	async updateChatName(
		chatId: string,
		pinedName: string
	): Promise<Result<null, string>> {
		try {
			return {
				status: "ok",
				data: await TAURI_INVOKE("update_chat_name", { chatId, pinedName }),
			};
		} catch (e) {
			if (e instanceof Error) throw e;
			else return { status: "error", error: e as any };
		}
	},
	async mergeBoardNote(
		id: string,
		patch: BoardNotePatch
	): Promise<Result<null, string>> {
		try {
			return {
				status: "ok",
				data: await TAURI_INVOKE("merge_board_note", { id, patch }),
			};
		} catch (e) {
			if (e instanceof Error) throw e;
			else return { status: "error", error: e as any };
		}
	},
	async createBoardNote(
		boardNote: BoardNoteCreate
	): Promise<Result<string, string>> {
		try {
			return {
				status: "ok",
				data: await TAURI_INVOKE("create_board_note", { boardNote }),
			};
		} catch (e) {
			if (e instanceof Error) throw e;
			else return { status: "error", error: e as any };
		}
	},
	async deleteBoardNote(id: string): Promise<Result<null, string>> {
		try {
			return {
				status: "ok",
				data: await TAURI_INVOKE("delete_board_note", { id }),
			};
		} catch (e) {
			if (e instanceof Error) throw e;
			else return { status: "error", error: e as any };
		}
	},
	async getMessages(chatId: string): Promise<Result<Chat[], string>> {
		try {
			return {
				status: "ok",
				data: await TAURI_INVOKE("get_messages", { chatId }),
			};
		} catch (e) {
			if (e instanceof Error) throw e;
			else return { status: "error", error: e as any };
		}
	},
	async getBoardNotes(chatId: string): Promise<Result<BoardNote[], string>> {
		try {
			return {
				status: "ok",
				data: await TAURI_INVOKE("get_board_notes", { chatId }),
			};
		} catch (e) {
			if (e instanceof Error) throw e;
			else return { status: "error", error: e as any };
		}
	},
};

/** user-defined events **/

/** user-defined constants **/

/** user-defined types **/

export type BoardNote = {
	x: number;
	y: number;
	z: number;
	width: number;
	height: number;
	color: string;
	question_id: string | null;
	chat_id: string;
};
export type BoardNoteCreate = {
	x?: number | null;
	y?: number | null;
	z?: number | null;
	width?: number | null;
	height?: number | null;
	color?: string | null;
	question_id?: string | null;
	chat_id?: string | null;
};
export type BoardNotePatch = {
	x?: number | null;
	y?: number | null;
	z?: number | null;
	width?: number | null;
	height?: number | null;
	color?: string | null;
	question_id?: string | null;
	chat_id?: string | null;
};
export type Chat = {
	id: string;
	username: string | null;
	first_name: string | null;
	last_name: string | null;
	phone: string | null;
	is_pinned: boolean | null;
	pined_name: string | null;
};
export type WordDefinition = { id: string; text: string };

/** tauri-specta globals **/

import {
	Channel as TAURI_CHANNEL,
	invoke as TAURI_INVOKE,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		}
	);
}
