name: "check"
on:
  push:
    branches:
      - "**"

permissions:
  contents: read

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-latest
          - runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v5

      - uses: DeterminateSystems/nix-installer-action@main

      - uses: cachix/cachix-action@v16
        with:
          name: nickcomua
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Nix flake check
        run: nix flake check --accept-flake-config --print-build-logs
